// Code generated by pigeon DO NOT EDIT.
package bexpr

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Input",
			pos:  position{line: 11, col: 1, offset: 98},
			expr: &actionExpr{
				pos: position{line: 11, col: 10, offset: 107},
				run: (*parser).callonInput1,
				expr: &seqExpr{
					pos: position{line: 11, col: 10, offset: 107},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 11, col: 10, offset: 107},
							expr: &ruleRefExpr{
								pos:  position{line: 11, col: 10, offset: 107},
								name: "_",
							},
						},
						&labeledExpr{
							pos:   position{line: 11, col: 13, offset: 110},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 11, col: 18, offset: 115},
								name: "OrExpression",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 11, col: 31, offset: 128},
							expr: &ruleRefExpr{
								pos:  position{line: 11, col: 31, offset: 128},
								name: "_",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 11, col: 34, offset: 131},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "OrExpression",
			pos:  position{line: 15, col: 1, offset: 160},
			expr: &choiceExpr{
				pos: position{line: 15, col: 17, offset: 176},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 15, col: 17, offset: 176},
						run: (*parser).callonOrExpression2,
						expr: &seqExpr{
							pos: position{line: 15, col: 17, offset: 176},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 15, col: 17, offset: 176},
									label: "left",
									expr: &ruleRefExpr{
										pos:  position{line: 15, col: 22, offset: 181},
										name: "AndExpression",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 15, col: 36, offset: 195},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 15, col: 38, offset: 197},
									val:        "or",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 15, col: 43, offset: 202},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 15, col: 45, offset: 204},
									label: "right",
									expr: &ruleRefExpr{
										pos:  position{line: 15, col: 51, offset: 210},
										name: "AndExpression",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 21, col: 5, offset: 343},
						run: (*parser).callonOrExpression11,
						expr: &labeledExpr{
							pos:   position{line: 21, col: 5, offset: 343},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 21, col: 10, offset: 348},
								name: "AndExpression",
							},
						},
					},
				},
			},
		},
		{
			name: "AndExpression",
			pos:  position{line: 25, col: 1, offset: 387},
			expr: &choiceExpr{
				pos: position{line: 25, col: 18, offset: 404},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 25, col: 18, offset: 404},
						run: (*parser).callonAndExpression2,
						expr: &seqExpr{
							pos: position{line: 25, col: 18, offset: 404},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 25, col: 18, offset: 404},
									label: "left",
									expr: &ruleRefExpr{
										pos:  position{line: 25, col: 23, offset: 409},
										name: "NotExpression",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 25, col: 37, offset: 423},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 25, col: 39, offset: 425},
									val:        "and",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 25, col: 45, offset: 431},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 25, col: 47, offset: 433},
									label: "right",
									expr: &ruleRefExpr{
										pos:  position{line: 25, col: 53, offset: 439},
										name: "NotExpression",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 31, col: 5, offset: 573},
						run: (*parser).callonAndExpression11,
						expr: &labeledExpr{
							pos:   position{line: 31, col: 5, offset: 573},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 31, col: 10, offset: 578},
								name: "NotExpression",
							},
						},
					},
				},
			},
		},
		{
			name: "NotExpression",
			pos:  position{line: 35, col: 1, offset: 617},
			expr: &choiceExpr{
				pos: position{line: 35, col: 18, offset: 634},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 35, col: 18, offset: 634},
						run: (*parser).callonNotExpression2,
						expr: &seqExpr{
							pos: position{line: 35, col: 18, offset: 634},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 35, col: 18, offset: 634},
									val:        "not",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 35, col: 24, offset: 640},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 35, col: 26, offset: 642},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 35, col: 31, offset: 647},
										name: "NotExpression",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 40, col: 5, offset: 755},
						run: (*parser).callonNotExpression8,
						expr: &labeledExpr{
							pos:   position{line: 40, col: 5, offset: 755},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 40, col: 10, offset: 760},
								name: "ParenthesizedExpression",
							},
						},
					},
				},
			},
		},
		{
			name: "ParenthesizedExpression",
			pos:  position{line: 44, col: 1, offset: 809},
			expr: &choiceExpr{
				pos: position{line: 44, col: 28, offset: 836},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 44, col: 28, offset: 836},
						run: (*parser).callonParenthesizedExpression2,
						expr: &seqExpr{
							pos: position{line: 44, col: 28, offset: 836},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 44, col: 28, offset: 836},
									val:        "(",
									ignoreCase: false,
								},
								&zeroOrOneExpr{
									pos: position{line: 44, col: 32, offset: 840},
									expr: &ruleRefExpr{
										pos:  position{line: 44, col: 32, offset: 840},
										name: "_",
									},
								},
								&labeledExpr{
									pos:   position{line: 44, col: 35, offset: 843},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 44, col: 40, offset: 848},
										name: "OrExpression",
									},
								},
								&zeroOrOneExpr{
									pos: position{line: 44, col: 53, offset: 861},
									expr: &ruleRefExpr{
										pos:  position{line: 44, col: 53, offset: 861},
										name: "_",
									},
								},
								&litMatcher{
									pos:        position{line: 44, col: 56, offset: 864},
									val:        ")",
									ignoreCase: false,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 46, col: 5, offset: 894},
						run: (*parser).callonParenthesizedExpression12,
						expr: &labeledExpr{
							pos:   position{line: 46, col: 5, offset: 894},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 46, col: 10, offset: 899},
								name: "MatchExpression",
							},
						},
					},
				},
			},
		},
		{
			name: "MatchExpression",
			pos:  position{line: 50, col: 1, offset: 940},
			expr: &choiceExpr{
				pos: position{line: 50, col: 20, offset: 959},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 50, col: 20, offset: 959},
						run: (*parser).callonMatchExpression2,
						expr: &seqExpr{
							pos: position{line: 50, col: 20, offset: 959},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 50, col: 20, offset: 959},
									label: "selector",
									expr: &ruleRefExpr{
										pos:  position{line: 50, col: 29, offset: 968},
										name: "Selector",
									},
								},
								&zeroOrOneExpr{
									pos: position{line: 50, col: 38, offset: 977},
									expr: &ruleRefExpr{
										pos:  position{line: 50, col: 38, offset: 977},
										name: "_",
									},
								},
								&litMatcher{
									pos:        position{line: 50, col: 41, offset: 980},
									val:        "==",
									ignoreCase: false,
								},
								&zeroOrOneExpr{
									pos: position{line: 50, col: 46, offset: 985},
									expr: &ruleRefExpr{
										pos:  position{line: 50, col: 46, offset: 985},
										name: "_",
									},
								},
								&labeledExpr{
									pos:   position{line: 50, col: 49, offset: 988},
									label: "value",
									expr: &ruleRefExpr{
										pos:  position{line: 50, col: 55, offset: 994},
										name: "Value",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 51, col: 20, offset: 1126},
						run: (*parser).callonMatchExpression13,
						expr: &seqExpr{
							pos: position{line: 51, col: 20, offset: 1126},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 51, col: 20, offset: 1126},
									label: "selector",
									expr: &ruleRefExpr{
										pos:  position{line: 51, col: 29, offset: 1135},
										name: "Selector",
									},
								},
								&zeroOrOneExpr{
									pos: position{line: 51, col: 38, offset: 1144},
									expr: &ruleRefExpr{
										pos:  position{line: 51, col: 38, offset: 1144},
										name: "_",
									},
								},
								&litMatcher{
									pos:        position{line: 51, col: 41, offset: 1147},
									val:        "!=",
									ignoreCase: false,
								},
								&zeroOrOneExpr{
									pos: position{line: 51, col: 46, offset: 1152},
									expr: &ruleRefExpr{
										pos:  position{line: 51, col: 46, offset: 1152},
										name: "_",
									},
								},
								&labeledExpr{
									pos:   position{line: 51, col: 49, offset: 1155},
									label: "value",
									expr: &ruleRefExpr{
										pos:  position{line: 51, col: 55, offset: 1161},
										name: "Value",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 52, col: 20, offset: 1296},
						run: (*parser).callonMatchExpression24,
						expr: &seqExpr{
							pos: position{line: 52, col: 20, offset: 1296},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 52, col: 20, offset: 1296},
									label: "selector",
									expr: &ruleRefExpr{
										pos:  position{line: 52, col: 29, offset: 1305},
										name: "Selector",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 52, col: 38, offset: 1314},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 52, col: 40, offset: 1316},
									val:        "is",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 52, col: 45, offset: 1321},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 52, col: 47, offset: 1323},
									val:        "empty",
									ignoreCase: false,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 53, col: 20, offset: 1454},
						run: (*parser).callonMatchExpression32,
						expr: &seqExpr{
							pos: position{line: 53, col: 20, offset: 1454},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 53, col: 20, offset: 1454},
									label: "selector",
									expr: &ruleRefExpr{
										pos:  position{line: 53, col: 29, offset: 1463},
										name: "Selector",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 53, col: 38, offset: 1472},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 53, col: 40, offset: 1474},
									val:        "is",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 53, col: 45, offset: 1479},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 53, col: 47, offset: 1481},
									val:        "not",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 53, col: 53, offset: 1487},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 53, col: 55, offset: 1489},
									val:        "empty",
									ignoreCase: false,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 54, col: 20, offset: 1615},
						run: (*parser).callonMatchExpression42,
						expr: &seqExpr{
							pos: position{line: 54, col: 20, offset: 1615},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 54, col: 20, offset: 1615},
									label: "value",
									expr: &ruleRefExpr{
										pos:  position{line: 54, col: 26, offset: 1621},
										name: "Value",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 54, col: 32, offset: 1627},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 54, col: 34, offset: 1629},
									val:        "in",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 54, col: 39, offset: 1634},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 54, col: 41, offset: 1636},
									label: "selector",
									expr: &ruleRefExpr{
										pos:  position{line: 54, col: 50, offset: 1645},
										name: "Selector",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 55, col: 20, offset: 1780},
						run: (*parser).callonMatchExpression51,
						expr: &seqExpr{
							pos: position{line: 55, col: 20, offset: 1780},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 55, col: 20, offset: 1780},
									label: "value",
									expr: &ruleRefExpr{
										pos:  position{line: 55, col: 26, offset: 1786},
										name: "Value",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 55, col: 32, offset: 1792},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 55, col: 34, offset: 1794},
									val:        "not",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 55, col: 40, offset: 1800},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 55, col: 42, offset: 1802},
									val:        "in",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 55, col: 47, offset: 1807},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 55, col: 49, offset: 1809},
									label: "selector",
									expr: &ruleRefExpr{
										pos:  position{line: 55, col: 58, offset: 1818},
										name: "Selector",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Selector",
			pos:  position{line: 57, col: 1, offset: 1930},
			expr: &actionExpr{
				pos: position{line: 57, col: 13, offset: 1942},
				run: (*parser).callonSelector1,
				expr: &seqExpr{
					pos: position{line: 57, col: 13, offset: 1942},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 57, col: 13, offset: 1942},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 57, col: 19, offset: 1948},
								name: "Identifier",
							},
						},
						&labeledExpr{
							pos:   position{line: 57, col: 30, offset: 1959},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 57, col: 35, offset: 1964},
								expr: &seqExpr{
									pos: position{line: 57, col: 36, offset: 1965},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 57, col: 36, offset: 1965},
											val:        ".",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 57, col: 40, offset: 1969},
											name: "Identifier",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 70, col: 1, offset: 2192},
			expr: &actionExpr{
				pos: position{line: 70, col: 15, offset: 2206},
				run: (*parser).callonIdentifier1,
				expr: &seqExpr{
					pos: position{line: 70, col: 15, offset: 2206},
					exprs: []interface{}{
						&charClassMatcher{
							pos:        position{line: 70, col: 15, offset: 2206},
							val:        "[a-zA-Z]",
							ranges:     []rune{'a', 'z', 'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 70, col: 24, offset: 2215},
							expr: &charClassMatcher{
								pos:        position{line: 70, col: 24, offset: 2215},
								val:        "[a-zA-Z0-9_]",
								chars:      []rune{'_'},
								ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "Value",
			pos:  position{line: 74, col: 1, offset: 2263},
			expr: &choiceExpr{
				pos: position{line: 74, col: 10, offset: 2272},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 74, col: 10, offset: 2272},
						run: (*parser).callonValue2,
						expr: &labeledExpr{
							pos:   position{line: 74, col: 10, offset: 2272},
							label: "selector",
							expr: &ruleRefExpr{
								pos:  position{line: 74, col: 19, offset: 2281},
								name: "Selector",
							},
						},
					},
					&actionExpr{
						pos: position{line: 75, col: 10, offset: 2366},
						run: (*parser).callonValue5,
						expr: &labeledExpr{
							pos:   position{line: 75, col: 10, offset: 2366},
							label: "i",
							expr: &ruleRefExpr{
								pos:  position{line: 75, col: 12, offset: 2368},
								name: "IntLiteral",
							},
						},
					},
					&actionExpr{
						pos: position{line: 76, col: 10, offset: 2428},
						run: (*parser).callonValue8,
						expr: &labeledExpr{
							pos:   position{line: 76, col: 10, offset: 2428},
							label: "s",
							expr: &ruleRefExpr{
								pos:  position{line: 76, col: 12, offset: 2430},
								name: "StringLiteral",
							},
						},
					},
					&andCodeExpr{
						pos: position{line: 77, col: 10, offset: 2492},
						run: (*parser).callonValue11,
					},
				},
			},
		},
		{
			name: "IntLiteral",
			pos:  position{line: 79, col: 1, offset: 2539},
			expr: &actionExpr{
				pos: position{line: 79, col: 15, offset: 2553},
				run: (*parser).callonIntLiteral1,
				expr: &seqExpr{
					pos: position{line: 79, col: 15, offset: 2553},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 79, col: 15, offset: 2553},
							expr: &litMatcher{
								pos:        position{line: 79, col: 15, offset: 2553},
								val:        "-",
								ignoreCase: false,
							},
						},
						&charClassMatcher{
							pos:        position{line: 79, col: 20, offset: 2558},
							val:        "[1-9]",
							ranges:     []rune{'1', '9'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 79, col: 25, offset: 2563},
							expr: &charClassMatcher{
								pos:        position{line: 79, col: 25, offset: 2563},
								val:        "[0-9]",
								ranges:     []rune{'0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "StringLiteral",
			pos:  position{line: 83, col: 1, offset: 2605},
			expr: &choiceExpr{
				pos: position{line: 83, col: 18, offset: 2622},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 83, col: 18, offset: 2622},
						run: (*parser).callonStringLiteral2,
						expr: &choiceExpr{
							pos: position{line: 83, col: 19, offset: 2623},
							alternatives: []interface{}{
								&seqExpr{
									pos: position{line: 83, col: 19, offset: 2623},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 83, col: 19, offset: 2623},
											val:        "`",
											ignoreCase: false,
										},
										&zeroOrMoreExpr{
											pos: position{line: 83, col: 23, offset: 2627},
											expr: &ruleRefExpr{
												pos:  position{line: 83, col: 23, offset: 2627},
												name: "RawStringChar",
											},
										},
										&litMatcher{
											pos:        position{line: 83, col: 38, offset: 2642},
											val:        "`",
											ignoreCase: false,
										},
									},
								},
								&seqExpr{
									pos: position{line: 83, col: 44, offset: 2648},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 83, col: 44, offset: 2648},
											val:        "\"",
											ignoreCase: false,
										},
										&zeroOrMoreExpr{
											pos: position{line: 83, col: 48, offset: 2652},
											expr: &ruleRefExpr{
												pos:  position{line: 83, col: 48, offset: 2652},
												name: "DoubleStringChar",
											},
										},
										&litMatcher{
											pos:        position{line: 83, col: 66, offset: 2670},
											val:        "\"",
											ignoreCase: false,
										},
									},
								},
							},
						},
					},
					&seqExpr{
						pos: position{line: 85, col: 5, offset: 2722},
						exprs: []interface{}{
							&choiceExpr{
								pos: position{line: 85, col: 6, offset: 2723},
								alternatives: []interface{}{
									&litMatcher{
										pos:        position{line: 85, col: 6, offset: 2723},
										val:        "`",
										ignoreCase: false,
									},
									&litMatcher{
										pos:        position{line: 85, col: 12, offset: 2729},
										val:        "\"",
										ignoreCase: false,
									},
								},
							},
							&andCodeExpr{
								pos: position{line: 85, col: 17, offset: 2734},
								run: (*parser).callonStringLiteral18,
							},
						},
					},
				},
			},
		},
		{
			name: "RawStringChar",
			pos:  position{line: 87, col: 1, offset: 2789},
			expr: &seqExpr{
				pos: position{line: 87, col: 18, offset: 2806},
				exprs: []interface{}{
					&notExpr{
						pos: position{line: 87, col: 18, offset: 2806},
						expr: &litMatcher{
							pos:        position{line: 87, col: 19, offset: 2807},
							val:        "`",
							ignoreCase: false,
						},
					},
					&anyMatcher{
						line: 87, col: 23, offset: 2811,
					},
				},
			},
		},
		{
			name: "DoubleStringChar",
			pos:  position{line: 88, col: 1, offset: 2813},
			expr: &seqExpr{
				pos: position{line: 88, col: 21, offset: 2833},
				exprs: []interface{}{
					&notExpr{
						pos: position{line: 88, col: 21, offset: 2833},
						expr: &litMatcher{
							pos:        position{line: 88, col: 22, offset: 2834},
							val:        "\"",
							ignoreCase: false,
						},
					},
					&anyMatcher{
						line: 88, col: 26, offset: 2838,
					},
				},
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 90, col: 1, offset: 2841},
			expr: &oneOrMoreExpr{
				pos: position{line: 90, col: 19, offset: 2859},
				expr: &charClassMatcher{
					pos:        position{line: 90, col: 19, offset: 2859},
					val:        "[ \\t\\r\\n]",
					chars:      []rune{' ', '\t', '\r', '\n'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 92, col: 1, offset: 2871},
			expr: &notExpr{
				pos: position{line: 92, col: 8, offset: 2878},
				expr: &anyMatcher{
					line: 92, col: 9, offset: 2879,
				},
			},
		},
	},
}

func (c *current) onInput1(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonInput1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInput1(stack["expr"])
}

func (c *current) onOrExpression2(left, right interface{}) (interface{}, error) {
	return &BinaryExpr{
		Operator: BinaryOpOr,
		Left:     left.(Expr),
		Right:    right.(Expr),
	}, nil
}

func (p *parser) callonOrExpression2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrExpression2(stack["left"], stack["right"])
}

func (c *current) onOrExpression11(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonOrExpression11() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrExpression11(stack["expr"])
}

func (c *current) onAndExpression2(left, right interface{}) (interface{}, error) {
	return &BinaryExpr{
		Operator: BinaryOpAnd,
		Left:     left.(Expr),
		Right:    right.(Expr),
	}, nil
}

func (p *parser) callonAndExpression2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAndExpression2(stack["left"], stack["right"])
}

func (c *current) onAndExpression11(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonAndExpression11() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAndExpression11(stack["expr"])
}

func (c *current) onNotExpression2(expr interface{}) (interface{}, error) {
	return &UnaryExpr{
		Operator: UnaryOpNot,
		Operand:  expr.(Expr),
	}, nil
}

func (p *parser) callonNotExpression2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNotExpression2(stack["expr"])
}

func (c *current) onNotExpression8(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonNotExpression8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNotExpression8(stack["expr"])
}

func (c *current) onParenthesizedExpression2(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonParenthesizedExpression2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParenthesizedExpression2(stack["expr"])
}

func (c *current) onParenthesizedExpression12(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonParenthesizedExpression12() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParenthesizedExpression12(stack["expr"])
}

func (c *current) onMatchExpression2(selector, value interface{}) (interface{}, error) {
	return &MatchExpr{Selector: selector.(Selector), Operator: MatchEqual, Value: value.(*Value)}, nil
}

func (p *parser) callonMatchExpression2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchExpression2(stack["selector"], stack["value"])
}

func (c *current) onMatchExpression13(selector, value interface{}) (interface{}, error) {
	return &MatchExpr{Selector: selector.(Selector), Operator: MatchNotEqual, Value: value.(*Value)}, nil
}

func (p *parser) callonMatchExpression13() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchExpression13(stack["selector"], stack["value"])
}

func (c *current) onMatchExpression24(selector interface{}) (interface{}, error) {
	return &MatchExpr{Selector: selector.(Selector), Operator: MatchIsEmpty, Value: nil}, nil
}

func (p *parser) callonMatchExpression24() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchExpression24(stack["selector"])
}

func (c *current) onMatchExpression32(selector interface{}) (interface{}, error) {
	return &MatchExpr{Selector: selector.(Selector), Operator: MatchIsNotEmpty, Value: nil}, nil
}

func (p *parser) callonMatchExpression32() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchExpression32(stack["selector"])
}

func (c *current) onMatchExpression42(value, selector interface{}) (interface{}, error) {
	return &MatchExpr{Selector: selector.(Selector), Operator: MatchIn, Value: value.(*Value)}, nil
}

func (p *parser) callonMatchExpression42() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchExpression42(stack["value"], stack["selector"])
}

func (c *current) onMatchExpression51(value, selector interface{}) (interface{}, error) {
	return &MatchExpr{Selector: selector.(Selector), Operator: MatchNotIn, Value: value.(*Value)}, nil
}

func (p *parser) callonMatchExpression51() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchExpression51(stack["value"], stack["selector"])
}

func (c *current) onSelector1(first, rest interface{}) (interface{}, error) {
	sel := Selector{
		first.(string),
	}

	if rest != nil {
		for _, v := range rest.([]interface{}) {
			sel = append(sel, v.([]interface{})[1].(string))
		}
	}
	return sel, nil
}

func (p *parser) callonSelector1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSelector1(stack["first"], stack["rest"])
}

func (c *current) onIdentifier1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonIdentifier1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifier1()
}

func (c *current) onValue2(selector interface{}) (interface{}, error) {
	return &Value{Raw: strings.Join(selector.(Selector), ".")}, nil
}

func (p *parser) callonValue2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValue2(stack["selector"])
}

func (c *current) onValue5(i interface{}) (interface{}, error) {
	return &Value{Raw: i.(string)}, nil
}

func (p *parser) callonValue5() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValue5(stack["i"])
}

func (c *current) onValue8(s interface{}) (interface{}, error) {
	return &Value{Raw: s.(string)}, nil
}

func (p *parser) callonValue8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValue8(stack["s"])
}

func (c *current) onValue11() (bool, error) {
	return false, errors.New("Invalid Value")
}

func (p *parser) callonValue11() (bool, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValue11()
}

func (c *current) onIntLiteral1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonIntLiteral1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntLiteral1()
}

func (c *current) onStringLiteral2() (interface{}, error) {
	return strconv.Unquote(string(c.text))
}

func (p *parser) callonStringLiteral2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringLiteral2()
}

func (c *current) onStringLiteral18() (bool, error) {
	return false, errors.New("Invalid StringLiteral")
}

func (p *parser) callonStringLiteral18() (bool, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringLiteral18()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errNoMatch is returned if no match could be found.
	errNoMatch = errors.New("no match found")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (interface{}, error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return fmt.Sprintf("%d:%d [%d]", p.line, p.col, p.offset)
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match
}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos        position
	val        string
	chars      []rune
	ranges     []rune
	classes    []*unicode.RangeTable
	ignoreCase bool
	inverted   bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner  error
	pos    position
	prefix string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
	}
	p.setOptions(opts)
	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	recover bool
	debug   bool
	depth   int

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// stats
	exprCnt int
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position)
}

func (p *parser) addErrAt(err error, pos position) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String()}
	p.errs.add(pe)
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError {
		if n == 1 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	// start rule is rule [0]
	p.read() // advance to first rune
	val, ok := p.parseRule(g.rules[0])
	if !ok {
		if len(*p.errs) == 0 {
			// make sure this doesn't go out silently
			p.addErr(errNoMatch)
		}
		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint
	var ok bool

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.exprCnt++
	var val interface{}
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position)
		}
		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restore(pt)
	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn != utf8.RuneError {
		start := p.pt
		p.read()
		return p.sliceFrom(start), true
	}
	return nil, false
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	// can't match EOF
	if cur == utf8.RuneError {
		return nil, false
	}
	start := p.pt
	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				return nil, false
			}
			p.read()
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				return nil, false
			}
			p.read()
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				return nil, false
			}
			p.read()
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		return p.sliceFrom(start), true
	}
	return nil, false
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for _, alt := range ch.alternatives {
		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			return val, ok
		}
	}
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	p.pushV()
	_, ok := p.parseExpr(not.expr)
	p.popV()
	p.restore(pt)
	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	var vals []interface{}

	pt := p.pt
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}

func rangeTable(class string) *unicode.RangeTable {
	if rt, ok := unicode.Categories[class]; ok {
		return rt
	}
	if rt, ok := unicode.Properties[class]; ok {
		return rt
	}
	if rt, ok := unicode.Scripts[class]; ok {
		return rt
	}

	// cannot happen
	panic(fmt.Sprintf("invalid Unicode class: %s", class))
}
