// Code generated by pigeon; DO NOT EDIT.

package bexpr

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

// The Parse, ParseFile and ParseReader functions will return an error that
// also satisfies this interface.
type ErrorList interface {
	Errors() []error
}

func (list errList) Errors() []error {
	return list
}

// Each error in the ErrorList returned by Parse, ParseFile and ParseReader
// will conform to this interface.
type ParserError interface {
	error
	InnerError() error
	Pos() (int, int, int)
	Expected() []string
}

func (p *parserError) InnerError() error {
	return p.Inner
}

func (p *parserError) Pos() (line, col, offset int) {
	return p.pos.line, p.pos.col, p.pos.offset
}

func (p *parserError) Expected() []string {
	return p.expected
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Input",
			pos:  position{line: 42, col: 1, offset: 732},
			expr: &actionExpr{
				pos: position{line: 42, col: 10, offset: 741},
				run: (*parser).callonInput1,
				expr: &seqExpr{
					pos: position{line: 42, col: 10, offset: 741},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 42, col: 10, offset: 741},
							expr: &ruleRefExpr{
								pos:  position{line: 42, col: 10, offset: 741},
								name: "_",
							},
						},
						&labeledExpr{
							pos:   position{line: 42, col: 13, offset: 744},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 42, col: 18, offset: 749},
								name: "OrExpression",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 42, col: 31, offset: 762},
							expr: &ruleRefExpr{
								pos:  position{line: 42, col: 31, offset: 762},
								name: "_",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 42, col: 34, offset: 765},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "OrExpression",
			pos:  position{line: 46, col: 1, offset: 794},
			expr: &choiceExpr{
				pos: position{line: 46, col: 17, offset: 810},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 46, col: 17, offset: 810},
						run: (*parser).callonOrExpression2,
						expr: &seqExpr{
							pos: position{line: 46, col: 17, offset: 810},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 46, col: 17, offset: 810},
									label: "left",
									expr: &ruleRefExpr{
										pos:  position{line: 46, col: 22, offset: 815},
										name: "AndExpression",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 46, col: 36, offset: 829},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 46, col: 38, offset: 831},
									val:        "or",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 46, col: 43, offset: 836},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 46, col: 45, offset: 838},
									label: "right",
									expr: &ruleRefExpr{
										pos:  position{line: 46, col: 51, offset: 844},
										name: "AndExpression",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 52, col: 5, offset: 977},
						run: (*parser).callonOrExpression11,
						expr: &labeledExpr{
							pos:   position{line: 52, col: 5, offset: 977},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 52, col: 10, offset: 982},
								name: "AndExpression",
							},
						},
					},
				},
			},
		},
		{
			name: "AndExpression",
			pos:  position{line: 56, col: 1, offset: 1021},
			expr: &choiceExpr{
				pos: position{line: 56, col: 18, offset: 1038},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 56, col: 18, offset: 1038},
						run: (*parser).callonAndExpression2,
						expr: &seqExpr{
							pos: position{line: 56, col: 18, offset: 1038},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 56, col: 18, offset: 1038},
									label: "left",
									expr: &ruleRefExpr{
										pos:  position{line: 56, col: 23, offset: 1043},
										name: "NotExpression",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 56, col: 37, offset: 1057},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 56, col: 39, offset: 1059},
									val:        "and",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 56, col: 45, offset: 1065},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 56, col: 47, offset: 1067},
									label: "right",
									expr: &ruleRefExpr{
										pos:  position{line: 56, col: 53, offset: 1073},
										name: "NotExpression",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 62, col: 5, offset: 1207},
						run: (*parser).callonAndExpression11,
						expr: &labeledExpr{
							pos:   position{line: 62, col: 5, offset: 1207},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 62, col: 10, offset: 1212},
								name: "NotExpression",
							},
						},
					},
				},
			},
		},
		{
			name: "NotExpression",
			pos:  position{line: 66, col: 1, offset: 1251},
			expr: &choiceExpr{
				pos: position{line: 66, col: 18, offset: 1268},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 66, col: 18, offset: 1268},
						run: (*parser).callonNotExpression2,
						expr: &seqExpr{
							pos: position{line: 66, col: 18, offset: 1268},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 66, col: 18, offset: 1268},
									val:        "not",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 66, col: 24, offset: 1274},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 66, col: 26, offset: 1276},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 66, col: 31, offset: 1281},
										name: "NotExpression",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 71, col: 5, offset: 1389},
						run: (*parser).callonNotExpression8,
						expr: &labeledExpr{
							pos:   position{line: 71, col: 5, offset: 1389},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 71, col: 10, offset: 1394},
								name: "ParenthesizedExpression",
							},
						},
					},
				},
			},
		},
		{
			name: "ParenthesizedExpression",
			pos:  position{line: 75, col: 1, offset: 1443},
			expr: &choiceExpr{
				pos: position{line: 75, col: 28, offset: 1470},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 75, col: 28, offset: 1470},
						run: (*parser).callonParenthesizedExpression2,
						expr: &seqExpr{
							pos: position{line: 75, col: 28, offset: 1470},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 75, col: 28, offset: 1470},
									val:        "(",
									ignoreCase: false,
								},
								&zeroOrOneExpr{
									pos: position{line: 75, col: 32, offset: 1474},
									expr: &ruleRefExpr{
										pos:  position{line: 75, col: 32, offset: 1474},
										name: "_",
									},
								},
								&labeledExpr{
									pos:   position{line: 75, col: 35, offset: 1477},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 75, col: 40, offset: 1482},
										name: "OrExpression",
									},
								},
								&zeroOrOneExpr{
									pos: position{line: 75, col: 53, offset: 1495},
									expr: &ruleRefExpr{
										pos:  position{line: 75, col: 53, offset: 1495},
										name: "_",
									},
								},
								&litMatcher{
									pos:        position{line: 75, col: 56, offset: 1498},
									val:        ")",
									ignoreCase: false,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 77, col: 5, offset: 1528},
						run: (*parser).callonParenthesizedExpression12,
						expr: &labeledExpr{
							pos:   position{line: 77, col: 5, offset: 1528},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 77, col: 10, offset: 1533},
								name: "MatchExpression",
							},
						},
					},
					&seqExpr{
						pos: position{line: 79, col: 5, offset: 1575},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 79, col: 5, offset: 1575},
								val:        "(",
								ignoreCase: false,
							},
							&zeroOrOneExpr{
								pos: position{line: 79, col: 9, offset: 1579},
								expr: &ruleRefExpr{
									pos:  position{line: 79, col: 9, offset: 1579},
									name: "_",
								},
							},
							&ruleRefExpr{
								pos:  position{line: 79, col: 12, offset: 1582},
								name: "OrExpression",
							},
							&zeroOrOneExpr{
								pos: position{line: 79, col: 25, offset: 1595},
								expr: &ruleRefExpr{
									pos:  position{line: 79, col: 25, offset: 1595},
									name: "_",
								},
							},
							&notExpr{
								pos: position{line: 79, col: 28, offset: 1598},
								expr: &litMatcher{
									pos:        position{line: 79, col: 29, offset: 1599},
									val:        ")",
									ignoreCase: false,
								},
							},
							&andCodeExpr{
								pos: position{line: 79, col: 33, offset: 1603},
								run: (*parser).callonParenthesizedExpression24,
							},
						},
					},
				},
			},
		},
		{
			name:        "MatchExpression",
			displayName: "\"match\"",
			pos:         position{line: 83, col: 1, offset: 1662},
			expr: &choiceExpr{
				pos: position{line: 83, col: 28, offset: 1689},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 83, col: 28, offset: 1689},
						name: "MatchSelectorOpValue",
					},
					&ruleRefExpr{
						pos:  position{line: 83, col: 51, offset: 1712},
						name: "MatchSelectorOp",
					},
					&ruleRefExpr{
						pos:  position{line: 83, col: 69, offset: 1730},
						name: "MatchValueOpSelector",
					},
				},
			},
		},
		{
			name:        "MatchSelectorOpValue",
			displayName: "\"match\"",
			pos:         position{line: 85, col: 1, offset: 1752},
			expr: &actionExpr{
				pos: position{line: 85, col: 33, offset: 1784},
				run: (*parser).callonMatchSelectorOpValue1,
				expr: &seqExpr{
					pos: position{line: 85, col: 33, offset: 1784},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 85, col: 33, offset: 1784},
							label: "selector",
							expr: &ruleRefExpr{
								pos:  position{line: 85, col: 42, offset: 1793},
								name: "Selector",
							},
						},
						&labeledExpr{
							pos:   position{line: 85, col: 51, offset: 1802},
							label: "operator",
							expr: &choiceExpr{
								pos: position{line: 85, col: 61, offset: 1812},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 85, col: 61, offset: 1812},
										name: "MatchEqual",
									},
									&ruleRefExpr{
										pos:  position{line: 85, col: 74, offset: 1825},
										name: "MatchNotEqual",
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 85, col: 89, offset: 1840},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 85, col: 95, offset: 1846},
								name: "Value",
							},
						},
					},
				},
			},
		},
		{
			name:        "MatchSelectorOp",
			displayName: "\"match\"",
			pos:         position{line: 89, col: 1, offset: 1973},
			expr: &actionExpr{
				pos: position{line: 89, col: 28, offset: 2000},
				run: (*parser).callonMatchSelectorOp1,
				expr: &seqExpr{
					pos: position{line: 89, col: 28, offset: 2000},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 89, col: 28, offset: 2000},
							label: "selector",
							expr: &ruleRefExpr{
								pos:  position{line: 89, col: 37, offset: 2009},
								name: "Selector",
							},
						},
						&labeledExpr{
							pos:   position{line: 89, col: 46, offset: 2018},
							label: "operator",
							expr: &choiceExpr{
								pos: position{line: 89, col: 56, offset: 2028},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 89, col: 56, offset: 2028},
										name: "MatchIsEmpty",
									},
									&ruleRefExpr{
										pos:  position{line: 89, col: 71, offset: 2043},
										name: "MatchIsNotEmpty",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name:        "MatchValueOpSelector",
			displayName: "\"match\"",
			pos:         position{line: 93, col: 1, offset: 2170},
			expr: &choiceExpr{
				pos: position{line: 93, col: 33, offset: 2202},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 93, col: 33, offset: 2202},
						run: (*parser).callonMatchValueOpSelector2,
						expr: &seqExpr{
							pos: position{line: 93, col: 33, offset: 2202},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 93, col: 33, offset: 2202},
									label: "value",
									expr: &ruleRefExpr{
										pos:  position{line: 93, col: 39, offset: 2208},
										name: "Value",
									},
								},
								&labeledExpr{
									pos:   position{line: 93, col: 45, offset: 2214},
									label: "operator",
									expr: &choiceExpr{
										pos: position{line: 93, col: 55, offset: 2224},
										alternatives: []interface{}{
											&ruleRefExpr{
												pos:  position{line: 93, col: 55, offset: 2224},
												name: "MatchIn",
											},
											&ruleRefExpr{
												pos:  position{line: 93, col: 65, offset: 2234},
												name: "MatchNotIn",
											},
										},
									},
								},
								&labeledExpr{
									pos:   position{line: 93, col: 77, offset: 2246},
									label: "selector",
									expr: &ruleRefExpr{
										pos:  position{line: 93, col: 86, offset: 2255},
										name: "Selector",
									},
								},
							},
						},
					},
					&seqExpr{
						pos: position{line: 95, col: 5, offset: 2386},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 95, col: 5, offset: 2386},
								name: "Value",
							},
							&labeledExpr{
								pos:   position{line: 95, col: 11, offset: 2392},
								label: "operator",
								expr: &choiceExpr{
									pos: position{line: 95, col: 21, offset: 2402},
									alternatives: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 95, col: 21, offset: 2402},
											name: "MatchIn",
										},
										&ruleRefExpr{
											pos:  position{line: 95, col: 31, offset: 2412},
											name: "MatchNotIn",
										},
									},
								},
							},
							&notExpr{
								pos: position{line: 95, col: 43, offset: 2424},
								expr: &ruleRefExpr{
									pos:  position{line: 95, col: 44, offset: 2425},
									name: "Selector",
								},
							},
							&andCodeExpr{
								pos: position{line: 95, col: 53, offset: 2434},
								run: (*parser).callonMatchValueOpSelector20,
							},
						},
					},
				},
			},
		},
		{
			name: "MatchEqual",
			pos:  position{line: 99, col: 1, offset: 2488},
			expr: &actionExpr{
				pos: position{line: 99, col: 15, offset: 2502},
				run: (*parser).callonMatchEqual1,
				expr: &seqExpr{
					pos: position{line: 99, col: 15, offset: 2502},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 99, col: 15, offset: 2502},
							expr: &ruleRefExpr{
								pos:  position{line: 99, col: 15, offset: 2502},
								name: "_",
							},
						},
						&litMatcher{
							pos:        position{line: 99, col: 18, offset: 2505},
							val:        "==",
							ignoreCase: false,
						},
						&zeroOrOneExpr{
							pos: position{line: 99, col: 23, offset: 2510},
							expr: &ruleRefExpr{
								pos:  position{line: 99, col: 23, offset: 2510},
								name: "_",
							},
						},
					},
				},
			},
		},
		{
			name: "MatchNotEqual",
			pos:  position{line: 102, col: 1, offset: 2543},
			expr: &actionExpr{
				pos: position{line: 102, col: 18, offset: 2560},
				run: (*parser).callonMatchNotEqual1,
				expr: &seqExpr{
					pos: position{line: 102, col: 18, offset: 2560},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 102, col: 18, offset: 2560},
							expr: &ruleRefExpr{
								pos:  position{line: 102, col: 18, offset: 2560},
								name: "_",
							},
						},
						&litMatcher{
							pos:        position{line: 102, col: 21, offset: 2563},
							val:        "!=",
							ignoreCase: false,
						},
						&zeroOrOneExpr{
							pos: position{line: 102, col: 26, offset: 2568},
							expr: &ruleRefExpr{
								pos:  position{line: 102, col: 26, offset: 2568},
								name: "_",
							},
						},
					},
				},
			},
		},
		{
			name: "MatchIsEmpty",
			pos:  position{line: 105, col: 1, offset: 2604},
			expr: &actionExpr{
				pos: position{line: 105, col: 17, offset: 2620},
				run: (*parser).callonMatchIsEmpty1,
				expr: &seqExpr{
					pos: position{line: 105, col: 17, offset: 2620},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 105, col: 17, offset: 2620},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 105, col: 19, offset: 2622},
							val:        "is",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 105, col: 24, offset: 2627},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 105, col: 26, offset: 2629},
							val:        "empty",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "MatchIsNotEmpty",
			pos:  position{line: 108, col: 1, offset: 2669},
			expr: &actionExpr{
				pos: position{line: 108, col: 20, offset: 2688},
				run: (*parser).callonMatchIsNotEmpty1,
				expr: &seqExpr{
					pos: position{line: 108, col: 20, offset: 2688},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 108, col: 20, offset: 2688},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 108, col: 21, offset: 2689},
							val:        "is",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 108, col: 26, offset: 2694},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 108, col: 28, offset: 2696},
							val:        "not",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 108, col: 34, offset: 2702},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 108, col: 36, offset: 2704},
							val:        "empty",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "MatchIn",
			pos:  position{line: 111, col: 1, offset: 2747},
			expr: &actionExpr{
				pos: position{line: 111, col: 12, offset: 2758},
				run: (*parser).callonMatchIn1,
				expr: &seqExpr{
					pos: position{line: 111, col: 12, offset: 2758},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 111, col: 12, offset: 2758},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 111, col: 14, offset: 2760},
							val:        "in",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 111, col: 19, offset: 2765},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "MatchNotIn",
			pos:  position{line: 114, col: 1, offset: 2794},
			expr: &actionExpr{
				pos: position{line: 114, col: 15, offset: 2808},
				run: (*parser).callonMatchNotIn1,
				expr: &seqExpr{
					pos: position{line: 114, col: 15, offset: 2808},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 114, col: 15, offset: 2808},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 114, col: 17, offset: 2810},
							val:        "not",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 114, col: 23, offset: 2816},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 114, col: 25, offset: 2818},
							val:        "in",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 114, col: 30, offset: 2823},
							name: "_",
						},
					},
				},
			},
		},
		{
			name:        "Selector",
			displayName: "\"selector\"",
			pos:         position{line: 118, col: 1, offset: 2856},
			expr: &actionExpr{
				pos: position{line: 118, col: 24, offset: 2879},
				run: (*parser).callonSelector1,
				expr: &seqExpr{
					pos: position{line: 118, col: 24, offset: 2879},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 118, col: 24, offset: 2879},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 118, col: 30, offset: 2885},
								name: "Identifier",
							},
						},
						&labeledExpr{
							pos:   position{line: 118, col: 41, offset: 2896},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 118, col: 46, offset: 2901},
								expr: &ruleRefExpr{
									pos:  position{line: 118, col: 46, offset: 2901},
									name: "SelectorOrIndex",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 131, col: 1, offset: 3108},
			expr: &actionExpr{
				pos: position{line: 131, col: 15, offset: 3122},
				run: (*parser).callonIdentifier1,
				expr: &seqExpr{
					pos: position{line: 131, col: 15, offset: 3122},
					exprs: []interface{}{
						&charClassMatcher{
							pos:        position{line: 131, col: 15, offset: 3122},
							val:        "[a-zA-Z]",
							ranges:     []rune{'a', 'z', 'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 131, col: 24, offset: 3131},
							expr: &charClassMatcher{
								pos:        position{line: 131, col: 24, offset: 3131},
								val:        "[a-zA-Z0-9_]",
								chars:      []rune{'_'},
								ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "SelectorOrIndex",
			pos:  position{line: 135, col: 1, offset: 3180},
			expr: &choiceExpr{
				pos: position{line: 135, col: 20, offset: 3199},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 135, col: 20, offset: 3199},
						run: (*parser).callonSelectorOrIndex2,
						expr: &seqExpr{
							pos: position{line: 135, col: 20, offset: 3199},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 135, col: 20, offset: 3199},
									val:        ".",
									ignoreCase: false,
								},
								&labeledExpr{
									pos:   position{line: 135, col: 24, offset: 3203},
									label: "ident",
									expr: &ruleRefExpr{
										pos:  position{line: 135, col: 30, offset: 3209},
										name: "Identifier",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 137, col: 5, offset: 3247},
						run: (*parser).callonSelectorOrIndex7,
						expr: &labeledExpr{
							pos:   position{line: 137, col: 5, offset: 3247},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 137, col: 10, offset: 3252},
								name: "IndexExpression",
							},
						},
					},
				},
			},
		},
		{
			name:        "IndexExpression",
			displayName: "\"index\"",
			pos:         position{line: 141, col: 1, offset: 3293},
			expr: &choiceExpr{
				pos: position{line: 141, col: 28, offset: 3320},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 141, col: 28, offset: 3320},
						run: (*parser).callonIndexExpression2,
						expr: &seqExpr{
							pos: position{line: 141, col: 28, offset: 3320},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 141, col: 28, offset: 3320},
									val:        "[",
									ignoreCase: false,
								},
								&zeroOrOneExpr{
									pos: position{line: 141, col: 32, offset: 3324},
									expr: &ruleRefExpr{
										pos:  position{line: 141, col: 32, offset: 3324},
										name: "_",
									},
								},
								&labeledExpr{
									pos:   position{line: 141, col: 35, offset: 3327},
									label: "lit",
									expr: &ruleRefExpr{
										pos:  position{line: 141, col: 39, offset: 3331},
										name: "StringLiteral",
									},
								},
								&zeroOrOneExpr{
									pos: position{line: 141, col: 53, offset: 3345},
									expr: &ruleRefExpr{
										pos:  position{line: 141, col: 53, offset: 3345},
										name: "_",
									},
								},
								&litMatcher{
									pos:        position{line: 141, col: 56, offset: 3348},
									val:        "]",
									ignoreCase: false,
								},
							},
						},
					},
					&seqExpr{
						pos: position{line: 143, col: 5, offset: 3377},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 143, col: 5, offset: 3377},
								val:        "[",
								ignoreCase: false,
							},
							&zeroOrOneExpr{
								pos: position{line: 143, col: 9, offset: 3381},
								expr: &ruleRefExpr{
									pos:  position{line: 143, col: 9, offset: 3381},
									name: "_",
								},
							},
							&notExpr{
								pos: position{line: 143, col: 12, offset: 3384},
								expr: &ruleRefExpr{
									pos:  position{line: 143, col: 13, offset: 3385},
									name: "StringLiteral",
								},
							},
							&andCodeExpr{
								pos: position{line: 143, col: 27, offset: 3399},
								run: (*parser).callonIndexExpression18,
							},
						},
					},
					&seqExpr{
						pos: position{line: 145, col: 5, offset: 3451},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 145, col: 5, offset: 3451},
								val:        "[",
								ignoreCase: false,
							},
							&zeroOrOneExpr{
								pos: position{line: 145, col: 9, offset: 3455},
								expr: &ruleRefExpr{
									pos:  position{line: 145, col: 9, offset: 3455},
									name: "_",
								},
							},
							&ruleRefExpr{
								pos:  position{line: 145, col: 12, offset: 3458},
								name: "StringLiteral",
							},
							&zeroOrOneExpr{
								pos: position{line: 145, col: 26, offset: 3472},
								expr: &ruleRefExpr{
									pos:  position{line: 145, col: 26, offset: 3472},
									name: "_",
								},
							},
							&notExpr{
								pos: position{line: 145, col: 29, offset: 3475},
								expr: &litMatcher{
									pos:        position{line: 145, col: 30, offset: 3476},
									val:        "]",
									ignoreCase: false,
								},
							},
							&andCodeExpr{
								pos: position{line: 145, col: 34, offset: 3480},
								run: (*parser).callonIndexExpression28,
							},
						},
					},
				},
			},
		},
		{
			name:        "Value",
			displayName: "\"value\"",
			pos:         position{line: 149, col: 1, offset: 3543},
			expr: &choiceExpr{
				pos: position{line: 149, col: 18, offset: 3560},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 149, col: 18, offset: 3560},
						run: (*parser).callonValue2,
						expr: &labeledExpr{
							pos:   position{line: 149, col: 18, offset: 3560},
							label: "selector",
							expr: &ruleRefExpr{
								pos:  position{line: 149, col: 27, offset: 3569},
								name: "Selector",
							},
						},
					},
					&actionExpr{
						pos: position{line: 150, col: 10, offset: 3654},
						run: (*parser).callonValue5,
						expr: &labeledExpr{
							pos:   position{line: 150, col: 10, offset: 3654},
							label: "i",
							expr: &ruleRefExpr{
								pos:  position{line: 150, col: 12, offset: 3656},
								name: "IntLiteral",
							},
						},
					},
					&actionExpr{
						pos: position{line: 151, col: 10, offset: 3716},
						run: (*parser).callonValue8,
						expr: &labeledExpr{
							pos:   position{line: 151, col: 10, offset: 3716},
							label: "s",
							expr: &ruleRefExpr{
								pos:  position{line: 151, col: 12, offset: 3718},
								name: "StringLiteral",
							},
						},
					},
				},
			},
		},
		{
			name:        "IntLiteral",
			displayName: "\"integer\"",
			pos:         position{line: 153, col: 1, offset: 3772},
			expr: &choiceExpr{
				pos: position{line: 153, col: 25, offset: 3796},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 153, col: 25, offset: 3796},
						run: (*parser).callonIntLiteral2,
						expr: &seqExpr{
							pos: position{line: 153, col: 25, offset: 3796},
							exprs: []interface{}{
								&zeroOrOneExpr{
									pos: position{line: 153, col: 25, offset: 3796},
									expr: &litMatcher{
										pos:        position{line: 153, col: 25, offset: 3796},
										val:        "-",
										ignoreCase: false,
									},
								},
								&charClassMatcher{
									pos:        position{line: 153, col: 30, offset: 3801},
									val:        "[1-9]",
									ranges:     []rune{'1', '9'},
									ignoreCase: false,
									inverted:   false,
								},
								&zeroOrMoreExpr{
									pos: position{line: 153, col: 35, offset: 3806},
									expr: &charClassMatcher{
										pos:        position{line: 153, col: 35, offset: 3806},
										val:        "[0-9]",
										ranges:     []rune{'0', '9'},
										ignoreCase: false,
										inverted:   false,
									},
								},
								&andExpr{
									pos: position{line: 153, col: 42, offset: 3813},
									expr: &choiceExpr{
										pos: position{line: 153, col: 44, offset: 3815},
										alternatives: []interface{}{
											&ruleRefExpr{
												pos:  position{line: 153, col: 44, offset: 3815},
												name: "_",
											},
											&ruleRefExpr{
												pos:  position{line: 153, col: 48, offset: 3819},
												name: "EOF",
											},
										},
									},
								},
							},
						},
					},
					&seqExpr{
						pos: position{line: 155, col: 5, offset: 3859},
						exprs: []interface{}{
							&zeroOrOneExpr{
								pos: position{line: 155, col: 5, offset: 3859},
								expr: &litMatcher{
									pos:        position{line: 155, col: 5, offset: 3859},
									val:        "-",
									ignoreCase: false,
								},
							},
							&charClassMatcher{
								pos:        position{line: 155, col: 10, offset: 3864},
								val:        "[1-9]",
								ranges:     []rune{'1', '9'},
								ignoreCase: false,
								inverted:   false,
							},
							&zeroOrMoreExpr{
								pos: position{line: 155, col: 15, offset: 3869},
								expr: &charClassMatcher{
									pos:        position{line: 155, col: 15, offset: 3869},
									val:        "[0-9]",
									ranges:     []rune{'0', '9'},
									ignoreCase: false,
									inverted:   false,
								},
							},
							&notExpr{
								pos: position{line: 155, col: 22, offset: 3876},
								expr: &choiceExpr{
									pos: position{line: 155, col: 24, offset: 3878},
									alternatives: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 155, col: 24, offset: 3878},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 155, col: 28, offset: 3882},
											name: "EOF",
										},
									},
								},
							},
							&andCodeExpr{
								pos: position{line: 155, col: 33, offset: 3887},
								run: (*parser).callonIntLiteral23,
							},
						},
					},
				},
			},
		},
		{
			name:        "StringLiteral",
			displayName: "\"string\"",
			pos:         position{line: 159, col: 1, offset: 3947},
			expr: &choiceExpr{
				pos: position{line: 159, col: 27, offset: 3973},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 159, col: 27, offset: 3973},
						run: (*parser).callonStringLiteral2,
						expr: &choiceExpr{
							pos: position{line: 159, col: 28, offset: 3974},
							alternatives: []interface{}{
								&seqExpr{
									pos: position{line: 159, col: 28, offset: 3974},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 159, col: 28, offset: 3974},
											val:        "`",
											ignoreCase: false,
										},
										&zeroOrMoreExpr{
											pos: position{line: 159, col: 32, offset: 3978},
											expr: &ruleRefExpr{
												pos:  position{line: 159, col: 32, offset: 3978},
												name: "RawStringChar",
											},
										},
										&litMatcher{
											pos:        position{line: 159, col: 47, offset: 3993},
											val:        "`",
											ignoreCase: false,
										},
									},
								},
								&seqExpr{
									pos: position{line: 159, col: 53, offset: 3999},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 159, col: 53, offset: 3999},
											val:        "\"",
											ignoreCase: false,
										},
										&zeroOrMoreExpr{
											pos: position{line: 159, col: 57, offset: 4003},
											expr: &ruleRefExpr{
												pos:  position{line: 159, col: 57, offset: 4003},
												name: "DoubleStringChar",
											},
										},
										&litMatcher{
											pos:        position{line: 159, col: 75, offset: 4021},
											val:        "\"",
											ignoreCase: false,
										},
									},
								},
							},
						},
					},
					&seqExpr{
						pos: position{line: 161, col: 5, offset: 4073},
						exprs: []interface{}{
							&choiceExpr{
								pos: position{line: 161, col: 6, offset: 4074},
								alternatives: []interface{}{
									&seqExpr{
										pos: position{line: 161, col: 6, offset: 4074},
										exprs: []interface{}{
											&litMatcher{
												pos:        position{line: 161, col: 6, offset: 4074},
												val:        "`",
												ignoreCase: false,
											},
											&zeroOrMoreExpr{
												pos: position{line: 161, col: 10, offset: 4078},
												expr: &ruleRefExpr{
													pos:  position{line: 161, col: 10, offset: 4078},
													name: "RawStringChar",
												},
											},
										},
									},
									&seqExpr{
										pos: position{line: 161, col: 27, offset: 4095},
										exprs: []interface{}{
											&litMatcher{
												pos:        position{line: 161, col: 27, offset: 4095},
												val:        "\"",
												ignoreCase: false,
											},
											&zeroOrMoreExpr{
												pos: position{line: 161, col: 31, offset: 4099},
												expr: &ruleRefExpr{
													pos:  position{line: 161, col: 31, offset: 4099},
													name: "DoubleStringChar",
												},
											},
										},
									},
								},
							},
							&ruleRefExpr{
								pos:  position{line: 161, col: 50, offset: 4118},
								name: "EOF",
							},
							&andCodeExpr{
								pos: position{line: 161, col: 54, offset: 4122},
								run: (*parser).callonStringLiteral25,
							},
						},
					},
				},
			},
		},
		{
			name: "RawStringChar",
			pos:  position{line: 165, col: 1, offset: 4186},
			expr: &seqExpr{
				pos: position{line: 165, col: 18, offset: 4203},
				exprs: []interface{}{
					&notExpr{
						pos: position{line: 165, col: 18, offset: 4203},
						expr: &litMatcher{
							pos:        position{line: 165, col: 19, offset: 4204},
							val:        "`",
							ignoreCase: false,
						},
					},
					&anyMatcher{
						line: 165, col: 23, offset: 4208,
					},
				},
			},
		},
		{
			name: "DoubleStringChar",
			pos:  position{line: 166, col: 1, offset: 4210},
			expr: &seqExpr{
				pos: position{line: 166, col: 21, offset: 4230},
				exprs: []interface{}{
					&notExpr{
						pos: position{line: 166, col: 21, offset: 4230},
						expr: &litMatcher{
							pos:        position{line: 166, col: 22, offset: 4231},
							val:        "\"",
							ignoreCase: false,
						},
					},
					&anyMatcher{
						line: 166, col: 26, offset: 4235,
					},
				},
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 168, col: 1, offset: 4238},
			expr: &oneOrMoreExpr{
				pos: position{line: 168, col: 19, offset: 4256},
				expr: &charClassMatcher{
					pos:        position{line: 168, col: 19, offset: 4256},
					val:        "[ \\t\\r\\n]",
					chars:      []rune{' ', '\t', '\r', '\n'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 170, col: 1, offset: 4268},
			expr: &notExpr{
				pos: position{line: 170, col: 8, offset: 4275},
				expr: &anyMatcher{
					line: 170, col: 9, offset: 4276,
				},
			},
		},
	},
}

func (c *current) onInput1(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonInput1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInput1(stack["expr"])
}

func (c *current) onOrExpression2(left, right interface{}) (interface{}, error) {
	return &BinaryExpr{
		Operator: BinaryOpOr,
		Left:     left.(Expr),
		Right:    right.(Expr),
	}, nil
}

func (p *parser) callonOrExpression2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrExpression2(stack["left"], stack["right"])
}

func (c *current) onOrExpression11(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonOrExpression11() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrExpression11(stack["expr"])
}

func (c *current) onAndExpression2(left, right interface{}) (interface{}, error) {
	return &BinaryExpr{
		Operator: BinaryOpAnd,
		Left:     left.(Expr),
		Right:    right.(Expr),
	}, nil
}

func (p *parser) callonAndExpression2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAndExpression2(stack["left"], stack["right"])
}

func (c *current) onAndExpression11(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonAndExpression11() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAndExpression11(stack["expr"])
}

func (c *current) onNotExpression2(expr interface{}) (interface{}, error) {
	return &UnaryExpr{
		Operator: UnaryOpNot,
		Operand:  expr.(Expr),
	}, nil
}

func (p *parser) callonNotExpression2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNotExpression2(stack["expr"])
}

func (c *current) onNotExpression8(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonNotExpression8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNotExpression8(stack["expr"])
}

func (c *current) onParenthesizedExpression2(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonParenthesizedExpression2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParenthesizedExpression2(stack["expr"])
}

func (c *current) onParenthesizedExpression12(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonParenthesizedExpression12() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParenthesizedExpression12(stack["expr"])
}

func (c *current) onParenthesizedExpression24() (bool, error) {
	return false, errors.New("Unmatched parentheses")
}

func (p *parser) callonParenthesizedExpression24() (bool, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParenthesizedExpression24()
}

func (c *current) onMatchSelectorOpValue1(selector, operator, value interface{}) (interface{}, error) {
	return &MatchExpr{Selector: selector.(Selector), Operator: operator.(MatchOperator), Value: value.(*Value)}, nil
}

func (p *parser) callonMatchSelectorOpValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchSelectorOpValue1(stack["selector"], stack["operator"], stack["value"])
}

func (c *current) onMatchSelectorOp1(selector, operator interface{}) (interface{}, error) {
	return &MatchExpr{Selector: selector.(Selector), Operator: operator.(MatchOperator), Value: nil}, nil
}

func (p *parser) callonMatchSelectorOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchSelectorOp1(stack["selector"], stack["operator"])
}

func (c *current) onMatchValueOpSelector2(value, operator, selector interface{}) (interface{}, error) {
	return &MatchExpr{Selector: selector.(Selector), Operator: operator.(MatchOperator), Value: value.(*Value)}, nil
}

func (p *parser) callonMatchValueOpSelector2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchValueOpSelector2(stack["value"], stack["operator"], stack["selector"])
}

func (c *current) onMatchValueOpSelector20(operator interface{}) (bool, error) {
	return false, errors.New("Invalid selector")
}

func (p *parser) callonMatchValueOpSelector20() (bool, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchValueOpSelector20(stack["operator"])
}

func (c *current) onMatchEqual1() (interface{}, error) {
	return MatchEqual, nil
}

func (p *parser) callonMatchEqual1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchEqual1()
}

func (c *current) onMatchNotEqual1() (interface{}, error) {
	return MatchNotEqual, nil
}

func (p *parser) callonMatchNotEqual1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchNotEqual1()
}

func (c *current) onMatchIsEmpty1() (interface{}, error) {
	return MatchIsEmpty, nil
}

func (p *parser) callonMatchIsEmpty1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchIsEmpty1()
}

func (c *current) onMatchIsNotEmpty1() (interface{}, error) {
	return MatchIsNotEmpty, nil
}

func (p *parser) callonMatchIsNotEmpty1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchIsNotEmpty1()
}

func (c *current) onMatchIn1() (interface{}, error) {
	return MatchIn, nil
}

func (p *parser) callonMatchIn1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchIn1()
}

func (c *current) onMatchNotIn1() (interface{}, error) {
	return MatchNotIn, nil
}

func (p *parser) callonMatchNotIn1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchNotIn1()
}

func (c *current) onSelector1(first, rest interface{}) (interface{}, error) {
	sel := Selector{
		first.(string),
	}

	if rest != nil {
		for _, v := range rest.([]interface{}) {
			sel = append(sel, v.(string))
		}
	}
	return sel, nil
}

func (p *parser) callonSelector1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSelector1(stack["first"], stack["rest"])
}

func (c *current) onIdentifier1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonIdentifier1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifier1()
}

func (c *current) onSelectorOrIndex2(ident interface{}) (interface{}, error) {
	return ident, nil
}

func (p *parser) callonSelectorOrIndex2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSelectorOrIndex2(stack["ident"])
}

func (c *current) onSelectorOrIndex7(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonSelectorOrIndex7() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSelectorOrIndex7(stack["expr"])
}

func (c *current) onIndexExpression2(lit interface{}) (interface{}, error) {
	return lit, nil
}

func (p *parser) callonIndexExpression2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIndexExpression2(stack["lit"])
}

func (c *current) onIndexExpression18() (bool, error) {
	return false, errors.New("Invalid index")
}

func (p *parser) callonIndexExpression18() (bool, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIndexExpression18()
}

func (c *current) onIndexExpression28() (bool, error) {
	return false, errors.New("Unclosed index expression")
}

func (p *parser) callonIndexExpression28() (bool, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIndexExpression28()
}

func (c *current) onValue2(selector interface{}) (interface{}, error) {
	return &Value{Raw: strings.Join(selector.(Selector), ".")}, nil
}

func (p *parser) callonValue2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValue2(stack["selector"])
}

func (c *current) onValue5(i interface{}) (interface{}, error) {
	return &Value{Raw: i.(string)}, nil
}

func (p *parser) callonValue5() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValue5(stack["i"])
}

func (c *current) onValue8(s interface{}) (interface{}, error) {
	return &Value{Raw: s.(string)}, nil
}

func (p *parser) callonValue8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValue8(stack["s"])
}

func (c *current) onIntLiteral2() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonIntLiteral2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntLiteral2()
}

func (c *current) onIntLiteral23() (bool, error) {
	return false, errors.New("Invalid integer literal")
}

func (p *parser) callonIntLiteral23() (bool, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntLiteral23()
}

func (c *current) onStringLiteral2() (interface{}, error) {
	return strconv.Unquote(string(c.text))
}

func (p *parser) callonStringLiteral2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringLiteral2()
}

func (c *current) onStringLiteral25() (bool, error) {
	return false, errors.New("Unterminated string literal")
}

func (p *parser) callonStringLiteral25() (bool, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringLiteral25()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return fmt.Sprintf("%d:%d [%d]", p.line, p.col, p.offset)
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := make(storeDict, len(p.cur.state))
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return fmt.Sprintf("%s %s %s", strings.Join(list[:len(list)-1], sep), lastSep, list[len(list)-1])
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	ignoreCase := ""
	if lit.ignoreCase {
		ignoreCase = "i"
	}
	val := fmt.Sprintf("%q%s", lit.val, ignoreCase)
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, val)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, val)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
