// Code generated by pigeon; DO NOT EDIT.

package bexpr

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

/*
// The Parse, ParseFile and ParseReader functions will return an error that
// also satisfies this interface.
type ErrorList interface {
   Errors() []error
}

func (list errList) Errors() []error {
   return list
}

// Each error in the ErrorList returned by Parse, ParseFile and ParseReader
// will conform to this interface.
type ParserError interface {
   error
   InnerError() error
   Pos() (int, int, int)
   Expected() []string
}

func (p *parserError) InnerError() error {
   return p.Inner
}

func (p *parserError) Pos() (line, col, offset int) {
   return p.pos.line, p.pos.col, p.pos.offset
}

func (p *parserError) Expected() []string {
   return p.expected
}
*/

var g = &grammar{
	rules: []*rule{
		{
			name: "Input",
			pos:  position{line: 44, col: 1, offset: 738},
			expr: &actionExpr{
				pos: position{line: 44, col: 10, offset: 747},
				run: (*parser).callonInput1,
				expr: &seqExpr{
					pos: position{line: 44, col: 10, offset: 747},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 44, col: 10, offset: 747},
							expr: &ruleRefExpr{
								pos:  position{line: 44, col: 10, offset: 747},
								name: "_",
							},
						},
						&labeledExpr{
							pos:   position{line: 44, col: 13, offset: 750},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 44, col: 18, offset: 755},
								name: "OrExpression",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 44, col: 31, offset: 768},
							expr: &ruleRefExpr{
								pos:  position{line: 44, col: 31, offset: 768},
								name: "_",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 44, col: 34, offset: 771},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "OrExpression",
			pos:  position{line: 48, col: 1, offset: 800},
			expr: &choiceExpr{
				pos: position{line: 48, col: 17, offset: 816},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 48, col: 17, offset: 816},
						run: (*parser).callonOrExpression2,
						expr: &seqExpr{
							pos: position{line: 48, col: 17, offset: 816},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 48, col: 17, offset: 816},
									label: "left",
									expr: &ruleRefExpr{
										pos:  position{line: 48, col: 22, offset: 821},
										name: "AndExpression",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 48, col: 36, offset: 835},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 48, col: 38, offset: 837},
									val:        "or",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 48, col: 43, offset: 842},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 48, col: 45, offset: 844},
									label: "right",
									expr: &ruleRefExpr{
										pos:  position{line: 48, col: 51, offset: 850},
										name: "OrExpression",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 54, col: 5, offset: 982},
						run: (*parser).callonOrExpression11,
						expr: &labeledExpr{
							pos:   position{line: 54, col: 5, offset: 982},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 54, col: 10, offset: 987},
								name: "AndExpression",
							},
						},
					},
				},
			},
		},
		{
			name: "AndExpression",
			pos:  position{line: 58, col: 1, offset: 1026},
			expr: &choiceExpr{
				pos: position{line: 58, col: 18, offset: 1043},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 58, col: 18, offset: 1043},
						run: (*parser).callonAndExpression2,
						expr: &seqExpr{
							pos: position{line: 58, col: 18, offset: 1043},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 58, col: 18, offset: 1043},
									label: "left",
									expr: &ruleRefExpr{
										pos:  position{line: 58, col: 23, offset: 1048},
										name: "NotExpression",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 58, col: 37, offset: 1062},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 58, col: 39, offset: 1064},
									val:        "and",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 58, col: 45, offset: 1070},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 58, col: 47, offset: 1072},
									label: "right",
									expr: &ruleRefExpr{
										pos:  position{line: 58, col: 53, offset: 1078},
										name: "AndExpression",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 64, col: 5, offset: 1212},
						run: (*parser).callonAndExpression11,
						expr: &labeledExpr{
							pos:   position{line: 64, col: 5, offset: 1212},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 64, col: 10, offset: 1217},
								name: "NotExpression",
							},
						},
					},
				},
			},
		},
		{
			name: "NotExpression",
			pos:  position{line: 68, col: 1, offset: 1256},
			expr: &choiceExpr{
				pos: position{line: 68, col: 18, offset: 1273},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 68, col: 18, offset: 1273},
						run: (*parser).callonNotExpression2,
						expr: &seqExpr{
							pos: position{line: 68, col: 18, offset: 1273},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 68, col: 18, offset: 1273},
									val:        "not",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 68, col: 24, offset: 1279},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 68, col: 26, offset: 1281},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 68, col: 31, offset: 1286},
										name: "NotExpression",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 79, col: 5, offset: 1655},
						run: (*parser).callonNotExpression8,
						expr: &labeledExpr{
							pos:   position{line: 79, col: 5, offset: 1655},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 79, col: 10, offset: 1660},
								name: "ParenthesizedExpression",
							},
						},
					},
				},
			},
		},
		{
			name:        "ParenthesizedExpression",
			displayName: "\"grouping\"",
			pos:         position{line: 83, col: 1, offset: 1709},
			expr: &choiceExpr{
				pos: position{line: 83, col: 39, offset: 1747},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 83, col: 39, offset: 1747},
						run: (*parser).callonParenthesizedExpression2,
						expr: &seqExpr{
							pos: position{line: 83, col: 39, offset: 1747},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 83, col: 39, offset: 1747},
									val:        "(",
									ignoreCase: false,
								},
								&zeroOrOneExpr{
									pos: position{line: 83, col: 43, offset: 1751},
									expr: &ruleRefExpr{
										pos:  position{line: 83, col: 43, offset: 1751},
										name: "_",
									},
								},
								&labeledExpr{
									pos:   position{line: 83, col: 46, offset: 1754},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 83, col: 51, offset: 1759},
										name: "OrExpression",
									},
								},
								&zeroOrOneExpr{
									pos: position{line: 83, col: 64, offset: 1772},
									expr: &ruleRefExpr{
										pos:  position{line: 83, col: 64, offset: 1772},
										name: "_",
									},
								},
								&litMatcher{
									pos:        position{line: 83, col: 67, offset: 1775},
									val:        ")",
									ignoreCase: false,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 85, col: 5, offset: 1805},
						run: (*parser).callonParenthesizedExpression12,
						expr: &labeledExpr{
							pos:   position{line: 85, col: 5, offset: 1805},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 85, col: 10, offset: 1810},
								name: "MatchExpression",
							},
						},
					},
					&seqExpr{
						pos: position{line: 87, col: 5, offset: 1852},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 87, col: 5, offset: 1852},
								val:        "(",
								ignoreCase: false,
							},
							&zeroOrOneExpr{
								pos: position{line: 87, col: 9, offset: 1856},
								expr: &ruleRefExpr{
									pos:  position{line: 87, col: 9, offset: 1856},
									name: "_",
								},
							},
							&ruleRefExpr{
								pos:  position{line: 87, col: 12, offset: 1859},
								name: "OrExpression",
							},
							&zeroOrOneExpr{
								pos: position{line: 87, col: 25, offset: 1872},
								expr: &ruleRefExpr{
									pos:  position{line: 87, col: 25, offset: 1872},
									name: "_",
								},
							},
							&notExpr{
								pos: position{line: 87, col: 28, offset: 1875},
								expr: &litMatcher{
									pos:        position{line: 87, col: 29, offset: 1876},
									val:        ")",
									ignoreCase: false,
								},
							},
							&andCodeExpr{
								pos: position{line: 87, col: 33, offset: 1880},
								run: (*parser).callonParenthesizedExpression24,
							},
						},
					},
				},
			},
		},
		{
			name:        "MatchExpression",
			displayName: "\"match\"",
			pos:         position{line: 91, col: 1, offset: 1939},
			expr: &choiceExpr{
				pos: position{line: 91, col: 28, offset: 1966},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 91, col: 28, offset: 1966},
						name: "MatchSelectorOpValue",
					},
					&ruleRefExpr{
						pos:  position{line: 91, col: 51, offset: 1989},
						name: "MatchSelectorOp",
					},
					&ruleRefExpr{
						pos:  position{line: 91, col: 69, offset: 2007},
						name: "MatchValueOpSelector",
					},
				},
			},
		},
		{
			name:        "MatchSelectorOpValue",
			displayName: "\"match\"",
			pos:         position{line: 93, col: 1, offset: 2029},
			expr: &actionExpr{
				pos: position{line: 93, col: 33, offset: 2061},
				run: (*parser).callonMatchSelectorOpValue1,
				expr: &seqExpr{
					pos: position{line: 93, col: 33, offset: 2061},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 93, col: 33, offset: 2061},
							label: "selector",
							expr: &ruleRefExpr{
								pos:  position{line: 93, col: 42, offset: 2070},
								name: "Selector",
							},
						},
						&labeledExpr{
							pos:   position{line: 93, col: 51, offset: 2079},
							label: "operator",
							expr: &choiceExpr{
								pos: position{line: 93, col: 61, offset: 2089},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 93, col: 61, offset: 2089},
										name: "MatchEqual",
									},
									&ruleRefExpr{
										pos:  position{line: 93, col: 74, offset: 2102},
										name: "MatchNotEqual",
									},
									&ruleRefExpr{
										pos:  position{line: 93, col: 90, offset: 2118},
										name: "MatchContains",
									},
									&ruleRefExpr{
										pos:  position{line: 93, col: 106, offset: 2134},
										name: "MatchNotContains",
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 93, col: 124, offset: 2152},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 93, col: 130, offset: 2158},
								name: "Value",
							},
						},
					},
				},
			},
		},
		{
			name:        "MatchSelectorOp",
			displayName: "\"match\"",
			pos:         position{line: 97, col: 1, offset: 2285},
			expr: &actionExpr{
				pos: position{line: 97, col: 28, offset: 2312},
				run: (*parser).callonMatchSelectorOp1,
				expr: &seqExpr{
					pos: position{line: 97, col: 28, offset: 2312},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 97, col: 28, offset: 2312},
							label: "selector",
							expr: &ruleRefExpr{
								pos:  position{line: 97, col: 37, offset: 2321},
								name: "Selector",
							},
						},
						&labeledExpr{
							pos:   position{line: 97, col: 46, offset: 2330},
							label: "operator",
							expr: &choiceExpr{
								pos: position{line: 97, col: 56, offset: 2340},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 97, col: 56, offset: 2340},
										name: "MatchIsEmpty",
									},
									&ruleRefExpr{
										pos:  position{line: 97, col: 71, offset: 2355},
										name: "MatchIsNotEmpty",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name:        "MatchValueOpSelector",
			displayName: "\"match\"",
			pos:         position{line: 101, col: 1, offset: 2482},
			expr: &choiceExpr{
				pos: position{line: 101, col: 33, offset: 2514},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 101, col: 33, offset: 2514},
						run: (*parser).callonMatchValueOpSelector2,
						expr: &seqExpr{
							pos: position{line: 101, col: 33, offset: 2514},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 101, col: 33, offset: 2514},
									label: "value",
									expr: &ruleRefExpr{
										pos:  position{line: 101, col: 39, offset: 2520},
										name: "Value",
									},
								},
								&labeledExpr{
									pos:   position{line: 101, col: 45, offset: 2526},
									label: "operator",
									expr: &choiceExpr{
										pos: position{line: 101, col: 55, offset: 2536},
										alternatives: []interface{}{
											&ruleRefExpr{
												pos:  position{line: 101, col: 55, offset: 2536},
												name: "MatchIn",
											},
											&ruleRefExpr{
												pos:  position{line: 101, col: 65, offset: 2546},
												name: "MatchNotIn",
											},
										},
									},
								},
								&labeledExpr{
									pos:   position{line: 101, col: 77, offset: 2558},
									label: "selector",
									expr: &ruleRefExpr{
										pos:  position{line: 101, col: 86, offset: 2567},
										name: "Selector",
									},
								},
							},
						},
					},
					&seqExpr{
						pos: position{line: 103, col: 5, offset: 2698},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 103, col: 5, offset: 2698},
								name: "Value",
							},
							&labeledExpr{
								pos:   position{line: 103, col: 11, offset: 2704},
								label: "operator",
								expr: &choiceExpr{
									pos: position{line: 103, col: 21, offset: 2714},
									alternatives: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 103, col: 21, offset: 2714},
											name: "MatchIn",
										},
										&ruleRefExpr{
											pos:  position{line: 103, col: 31, offset: 2724},
											name: "MatchNotIn",
										},
									},
								},
							},
							&notExpr{
								pos: position{line: 103, col: 43, offset: 2736},
								expr: &ruleRefExpr{
									pos:  position{line: 103, col: 44, offset: 2737},
									name: "Selector",
								},
							},
							&andCodeExpr{
								pos: position{line: 103, col: 53, offset: 2746},
								run: (*parser).callonMatchValueOpSelector20,
							},
						},
					},
				},
			},
		},
		{
			name: "MatchEqual",
			pos:  position{line: 107, col: 1, offset: 2800},
			expr: &actionExpr{
				pos: position{line: 107, col: 15, offset: 2814},
				run: (*parser).callonMatchEqual1,
				expr: &seqExpr{
					pos: position{line: 107, col: 15, offset: 2814},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 107, col: 15, offset: 2814},
							expr: &ruleRefExpr{
								pos:  position{line: 107, col: 15, offset: 2814},
								name: "_",
							},
						},
						&litMatcher{
							pos:        position{line: 107, col: 18, offset: 2817},
							val:        "==",
							ignoreCase: false,
						},
						&zeroOrOneExpr{
							pos: position{line: 107, col: 23, offset: 2822},
							expr: &ruleRefExpr{
								pos:  position{line: 107, col: 23, offset: 2822},
								name: "_",
							},
						},
					},
				},
			},
		},
		{
			name: "MatchNotEqual",
			pos:  position{line: 110, col: 1, offset: 2855},
			expr: &actionExpr{
				pos: position{line: 110, col: 18, offset: 2872},
				run: (*parser).callonMatchNotEqual1,
				expr: &seqExpr{
					pos: position{line: 110, col: 18, offset: 2872},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 110, col: 18, offset: 2872},
							expr: &ruleRefExpr{
								pos:  position{line: 110, col: 18, offset: 2872},
								name: "_",
							},
						},
						&litMatcher{
							pos:        position{line: 110, col: 21, offset: 2875},
							val:        "!=",
							ignoreCase: false,
						},
						&zeroOrOneExpr{
							pos: position{line: 110, col: 26, offset: 2880},
							expr: &ruleRefExpr{
								pos:  position{line: 110, col: 26, offset: 2880},
								name: "_",
							},
						},
					},
				},
			},
		},
		{
			name: "MatchIsEmpty",
			pos:  position{line: 113, col: 1, offset: 2916},
			expr: &actionExpr{
				pos: position{line: 113, col: 17, offset: 2932},
				run: (*parser).callonMatchIsEmpty1,
				expr: &seqExpr{
					pos: position{line: 113, col: 17, offset: 2932},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 113, col: 17, offset: 2932},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 113, col: 19, offset: 2934},
							val:        "is",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 113, col: 24, offset: 2939},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 113, col: 26, offset: 2941},
							val:        "empty",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "MatchIsNotEmpty",
			pos:  position{line: 116, col: 1, offset: 2981},
			expr: &actionExpr{
				pos: position{line: 116, col: 20, offset: 3000},
				run: (*parser).callonMatchIsNotEmpty1,
				expr: &seqExpr{
					pos: position{line: 116, col: 20, offset: 3000},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 116, col: 20, offset: 3000},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 116, col: 21, offset: 3001},
							val:        "is",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 116, col: 26, offset: 3006},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 116, col: 28, offset: 3008},
							val:        "not",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 116, col: 34, offset: 3014},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 116, col: 36, offset: 3016},
							val:        "empty",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "MatchIn",
			pos:  position{line: 119, col: 1, offset: 3059},
			expr: &actionExpr{
				pos: position{line: 119, col: 12, offset: 3070},
				run: (*parser).callonMatchIn1,
				expr: &seqExpr{
					pos: position{line: 119, col: 12, offset: 3070},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 119, col: 12, offset: 3070},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 119, col: 14, offset: 3072},
							val:        "in",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 119, col: 19, offset: 3077},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "MatchNotIn",
			pos:  position{line: 122, col: 1, offset: 3106},
			expr: &actionExpr{
				pos: position{line: 122, col: 15, offset: 3120},
				run: (*parser).callonMatchNotIn1,
				expr: &seqExpr{
					pos: position{line: 122, col: 15, offset: 3120},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 122, col: 15, offset: 3120},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 122, col: 17, offset: 3122},
							val:        "not",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 122, col: 23, offset: 3128},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 122, col: 25, offset: 3130},
							val:        "in",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 122, col: 30, offset: 3135},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "MatchContains",
			pos:  position{line: 125, col: 1, offset: 3167},
			expr: &actionExpr{
				pos: position{line: 125, col: 18, offset: 3184},
				run: (*parser).callonMatchContains1,
				expr: &seqExpr{
					pos: position{line: 125, col: 18, offset: 3184},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 125, col: 18, offset: 3184},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 125, col: 20, offset: 3186},
							val:        "contains",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 125, col: 31, offset: 3197},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "MatchNotContains",
			pos:  position{line: 128, col: 1, offset: 3226},
			expr: &actionExpr{
				pos: position{line: 128, col: 21, offset: 3246},
				run: (*parser).callonMatchNotContains1,
				expr: &seqExpr{
					pos: position{line: 128, col: 21, offset: 3246},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 128, col: 21, offset: 3246},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 128, col: 23, offset: 3248},
							val:        "not",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 128, col: 29, offset: 3254},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 128, col: 31, offset: 3256},
							val:        "contains",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 128, col: 42, offset: 3267},
							name: "_",
						},
					},
				},
			},
		},
		{
			name:        "Selector",
			displayName: "\"selector\"",
			pos:         position{line: 133, col: 1, offset: 3301},
			expr: &actionExpr{
				pos: position{line: 133, col: 24, offset: 3324},
				run: (*parser).callonSelector1,
				expr: &seqExpr{
					pos: position{line: 133, col: 24, offset: 3324},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 133, col: 24, offset: 3324},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 133, col: 30, offset: 3330},
								name: "Identifier",
							},
						},
						&labeledExpr{
							pos:   position{line: 133, col: 41, offset: 3341},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 133, col: 46, offset: 3346},
								expr: &ruleRefExpr{
									pos:  position{line: 133, col: 46, offset: 3346},
									name: "SelectorOrIndex",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 146, col: 1, offset: 3553},
			expr: &actionExpr{
				pos: position{line: 146, col: 15, offset: 3567},
				run: (*parser).callonIdentifier1,
				expr: &seqExpr{
					pos: position{line: 146, col: 15, offset: 3567},
					exprs: []interface{}{
						&charClassMatcher{
							pos:        position{line: 146, col: 15, offset: 3567},
							val:        "[a-zA-Z]",
							ranges:     []rune{'a', 'z', 'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 146, col: 24, offset: 3576},
							expr: &charClassMatcher{
								pos:        position{line: 146, col: 24, offset: 3576},
								val:        "[a-zA-Z0-9_]",
								chars:      []rune{'_'},
								ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "SelectorOrIndex",
			pos:  position{line: 150, col: 1, offset: 3625},
			expr: &choiceExpr{
				pos: position{line: 150, col: 20, offset: 3644},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 150, col: 20, offset: 3644},
						run: (*parser).callonSelectorOrIndex2,
						expr: &seqExpr{
							pos: position{line: 150, col: 20, offset: 3644},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 150, col: 20, offset: 3644},
									val:        ".",
									ignoreCase: false,
								},
								&labeledExpr{
									pos:   position{line: 150, col: 24, offset: 3648},
									label: "ident",
									expr: &ruleRefExpr{
										pos:  position{line: 150, col: 30, offset: 3654},
										name: "Identifier",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 152, col: 5, offset: 3692},
						run: (*parser).callonSelectorOrIndex7,
						expr: &labeledExpr{
							pos:   position{line: 152, col: 5, offset: 3692},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 152, col: 10, offset: 3697},
								name: "IndexExpression",
							},
						},
					},
				},
			},
		},
		{
			name:        "IndexExpression",
			displayName: "\"index\"",
			pos:         position{line: 156, col: 1, offset: 3738},
			expr: &choiceExpr{
				pos: position{line: 156, col: 28, offset: 3765},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 156, col: 28, offset: 3765},
						run: (*parser).callonIndexExpression2,
						expr: &seqExpr{
							pos: position{line: 156, col: 28, offset: 3765},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 156, col: 28, offset: 3765},
									val:        "[",
									ignoreCase: false,
								},
								&zeroOrOneExpr{
									pos: position{line: 156, col: 32, offset: 3769},
									expr: &ruleRefExpr{
										pos:  position{line: 156, col: 32, offset: 3769},
										name: "_",
									},
								},
								&labeledExpr{
									pos:   position{line: 156, col: 35, offset: 3772},
									label: "lit",
									expr: &ruleRefExpr{
										pos:  position{line: 156, col: 39, offset: 3776},
										name: "StringLiteral",
									},
								},
								&zeroOrOneExpr{
									pos: position{line: 156, col: 53, offset: 3790},
									expr: &ruleRefExpr{
										pos:  position{line: 156, col: 53, offset: 3790},
										name: "_",
									},
								},
								&litMatcher{
									pos:        position{line: 156, col: 56, offset: 3793},
									val:        "]",
									ignoreCase: false,
								},
							},
						},
					},
					&seqExpr{
						pos: position{line: 158, col: 5, offset: 3822},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 158, col: 5, offset: 3822},
								val:        "[",
								ignoreCase: false,
							},
							&zeroOrOneExpr{
								pos: position{line: 158, col: 9, offset: 3826},
								expr: &ruleRefExpr{
									pos:  position{line: 158, col: 9, offset: 3826},
									name: "_",
								},
							},
							&notExpr{
								pos: position{line: 158, col: 12, offset: 3829},
								expr: &ruleRefExpr{
									pos:  position{line: 158, col: 13, offset: 3830},
									name: "StringLiteral",
								},
							},
							&andCodeExpr{
								pos: position{line: 158, col: 27, offset: 3844},
								run: (*parser).callonIndexExpression18,
							},
						},
					},
					&seqExpr{
						pos: position{line: 160, col: 5, offset: 3896},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 160, col: 5, offset: 3896},
								val:        "[",
								ignoreCase: false,
							},
							&zeroOrOneExpr{
								pos: position{line: 160, col: 9, offset: 3900},
								expr: &ruleRefExpr{
									pos:  position{line: 160, col: 9, offset: 3900},
									name: "_",
								},
							},
							&ruleRefExpr{
								pos:  position{line: 160, col: 12, offset: 3903},
								name: "StringLiteral",
							},
							&zeroOrOneExpr{
								pos: position{line: 160, col: 26, offset: 3917},
								expr: &ruleRefExpr{
									pos:  position{line: 160, col: 26, offset: 3917},
									name: "_",
								},
							},
							&notExpr{
								pos: position{line: 160, col: 29, offset: 3920},
								expr: &litMatcher{
									pos:        position{line: 160, col: 30, offset: 3921},
									val:        "]",
									ignoreCase: false,
								},
							},
							&andCodeExpr{
								pos: position{line: 160, col: 34, offset: 3925},
								run: (*parser).callonIndexExpression28,
							},
						},
					},
				},
			},
		},
		{
			name:        "Value",
			displayName: "\"value\"",
			pos:         position{line: 164, col: 1, offset: 3988},
			expr: &choiceExpr{
				pos: position{line: 164, col: 18, offset: 4005},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 164, col: 18, offset: 4005},
						run: (*parser).callonValue2,
						expr: &labeledExpr{
							pos:   position{line: 164, col: 18, offset: 4005},
							label: "selector",
							expr: &ruleRefExpr{
								pos:  position{line: 164, col: 27, offset: 4014},
								name: "Selector",
							},
						},
					},
					&actionExpr{
						pos: position{line: 165, col: 10, offset: 4099},
						run: (*parser).callonValue5,
						expr: &labeledExpr{
							pos:   position{line: 165, col: 10, offset: 4099},
							label: "n",
							expr: &ruleRefExpr{
								pos:  position{line: 165, col: 12, offset: 4101},
								name: "NumberLiteral",
							},
						},
					},
					&actionExpr{
						pos: position{line: 166, col: 10, offset: 4164},
						run: (*parser).callonValue8,
						expr: &labeledExpr{
							pos:   position{line: 166, col: 10, offset: 4164},
							label: "s",
							expr: &ruleRefExpr{
								pos:  position{line: 166, col: 12, offset: 4166},
								name: "StringLiteral",
							},
						},
					},
				},
			},
		},
		{
			name:        "NumberLiteral",
			displayName: "\"number\"",
			pos:         position{line: 168, col: 1, offset: 4220},
			expr: &choiceExpr{
				pos: position{line: 168, col: 27, offset: 4246},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 168, col: 27, offset: 4246},
						run: (*parser).callonNumberLiteral2,
						expr: &seqExpr{
							pos: position{line: 168, col: 27, offset: 4246},
							exprs: []interface{}{
								&zeroOrOneExpr{
									pos: position{line: 168, col: 27, offset: 4246},
									expr: &litMatcher{
										pos:        position{line: 168, col: 27, offset: 4246},
										val:        "-",
										ignoreCase: false,
									},
								},
								&ruleRefExpr{
									pos:  position{line: 168, col: 32, offset: 4251},
									name: "IntegerOrFloat",
								},
								&andExpr{
									pos: position{line: 168, col: 47, offset: 4266},
									expr: &choiceExpr{
										pos: position{line: 168, col: 49, offset: 4268},
										alternatives: []interface{}{
											&ruleRefExpr{
												pos:  position{line: 168, col: 49, offset: 4268},
												name: "_",
											},
											&ruleRefExpr{
												pos:  position{line: 168, col: 53, offset: 4272},
												name: "EOF",
											},
										},
									},
								},
							},
						},
					},
					&seqExpr{
						pos: position{line: 170, col: 5, offset: 4313},
						exprs: []interface{}{
							&zeroOrOneExpr{
								pos: position{line: 170, col: 5, offset: 4313},
								expr: &litMatcher{
									pos:        position{line: 170, col: 5, offset: 4313},
									val:        "-",
									ignoreCase: false,
								},
							},
							&ruleRefExpr{
								pos:  position{line: 170, col: 10, offset: 4318},
								name: "IntegerOrFloat",
							},
							&notExpr{
								pos: position{line: 170, col: 25, offset: 4333},
								expr: &choiceExpr{
									pos: position{line: 170, col: 27, offset: 4335},
									alternatives: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 170, col: 27, offset: 4335},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 170, col: 31, offset: 4339},
											name: "EOF",
										},
									},
								},
							},
							&andCodeExpr{
								pos: position{line: 170, col: 36, offset: 4344},
								run: (*parser).callonNumberLiteral19,
							},
						},
					},
				},
			},
		},
		{
			name: "IntegerOrFloat",
			pos:  position{line: 174, col: 1, offset: 4404},
			expr: &seqExpr{
				pos: position{line: 174, col: 19, offset: 4422},
				exprs: []interface{}{
					&choiceExpr{
						pos: position{line: 174, col: 20, offset: 4423},
						alternatives: []interface{}{
							&litMatcher{
								pos:        position{line: 174, col: 20, offset: 4423},
								val:        "0",
								ignoreCase: false,
							},
							&seqExpr{
								pos: position{line: 174, col: 26, offset: 4429},
								exprs: []interface{}{
									&charClassMatcher{
										pos:        position{line: 174, col: 26, offset: 4429},
										val:        "[1-9]",
										ranges:     []rune{'1', '9'},
										ignoreCase: false,
										inverted:   false,
									},
									&zeroOrMoreExpr{
										pos: position{line: 174, col: 31, offset: 4434},
										expr: &charClassMatcher{
											pos:        position{line: 174, col: 31, offset: 4434},
											val:        "[0-9]",
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
								},
							},
						},
					},
					&zeroOrOneExpr{
						pos: position{line: 174, col: 39, offset: 4442},
						expr: &seqExpr{
							pos: position{line: 174, col: 40, offset: 4443},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 174, col: 40, offset: 4443},
									val:        ".",
									ignoreCase: false,
								},
								&oneOrMoreExpr{
									pos: position{line: 174, col: 44, offset: 4447},
									expr: &charClassMatcher{
										pos:        position{line: 174, col: 44, offset: 4447},
										val:        "[0-9]",
										ranges:     []rune{'0', '9'},
										ignoreCase: false,
										inverted:   false,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name:        "StringLiteral",
			displayName: "\"string\"",
			pos:         position{line: 176, col: 1, offset: 4457},
			expr: &choiceExpr{
				pos: position{line: 176, col: 27, offset: 4483},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 176, col: 27, offset: 4483},
						run: (*parser).callonStringLiteral2,
						expr: &choiceExpr{
							pos: position{line: 176, col: 28, offset: 4484},
							alternatives: []interface{}{
								&seqExpr{
									pos: position{line: 176, col: 28, offset: 4484},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 176, col: 28, offset: 4484},
											val:        "`",
											ignoreCase: false,
										},
										&zeroOrMoreExpr{
											pos: position{line: 176, col: 32, offset: 4488},
											expr: &ruleRefExpr{
												pos:  position{line: 176, col: 32, offset: 4488},
												name: "RawStringChar",
											},
										},
										&litMatcher{
											pos:        position{line: 176, col: 47, offset: 4503},
											val:        "`",
											ignoreCase: false,
										},
									},
								},
								&seqExpr{
									pos: position{line: 176, col: 53, offset: 4509},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 176, col: 53, offset: 4509},
											val:        "\"",
											ignoreCase: false,
										},
										&zeroOrMoreExpr{
											pos: position{line: 176, col: 57, offset: 4513},
											expr: &ruleRefExpr{
												pos:  position{line: 176, col: 57, offset: 4513},
												name: "DoubleStringChar",
											},
										},
										&litMatcher{
											pos:        position{line: 176, col: 75, offset: 4531},
											val:        "\"",
											ignoreCase: false,
										},
									},
								},
							},
						},
					},
					&seqExpr{
						pos: position{line: 178, col: 5, offset: 4583},
						exprs: []interface{}{
							&choiceExpr{
								pos: position{line: 178, col: 6, offset: 4584},
								alternatives: []interface{}{
									&seqExpr{
										pos: position{line: 178, col: 6, offset: 4584},
										exprs: []interface{}{
											&litMatcher{
												pos:        position{line: 178, col: 6, offset: 4584},
												val:        "`",
												ignoreCase: false,
											},
											&zeroOrMoreExpr{
												pos: position{line: 178, col: 10, offset: 4588},
												expr: &ruleRefExpr{
													pos:  position{line: 178, col: 10, offset: 4588},
													name: "RawStringChar",
												},
											},
										},
									},
									&seqExpr{
										pos: position{line: 178, col: 27, offset: 4605},
										exprs: []interface{}{
											&litMatcher{
												pos:        position{line: 178, col: 27, offset: 4605},
												val:        "\"",
												ignoreCase: false,
											},
											&zeroOrMoreExpr{
												pos: position{line: 178, col: 31, offset: 4609},
												expr: &ruleRefExpr{
													pos:  position{line: 178, col: 31, offset: 4609},
													name: "DoubleStringChar",
												},
											},
										},
									},
								},
							},
							&ruleRefExpr{
								pos:  position{line: 178, col: 50, offset: 4628},
								name: "EOF",
							},
							&andCodeExpr{
								pos: position{line: 178, col: 54, offset: 4632},
								run: (*parser).callonStringLiteral25,
							},
						},
					},
				},
			},
		},
		{
			name: "RawStringChar",
			pos:  position{line: 182, col: 1, offset: 4696},
			expr: &seqExpr{
				pos: position{line: 182, col: 18, offset: 4713},
				exprs: []interface{}{
					&notExpr{
						pos: position{line: 182, col: 18, offset: 4713},
						expr: &litMatcher{
							pos:        position{line: 182, col: 19, offset: 4714},
							val:        "`",
							ignoreCase: false,
						},
					},
					&anyMatcher{
						line: 182, col: 23, offset: 4718,
					},
				},
			},
		},
		{
			name: "DoubleStringChar",
			pos:  position{line: 183, col: 1, offset: 4720},
			expr: &seqExpr{
				pos: position{line: 183, col: 21, offset: 4740},
				exprs: []interface{}{
					&notExpr{
						pos: position{line: 183, col: 21, offset: 4740},
						expr: &litMatcher{
							pos:        position{line: 183, col: 22, offset: 4741},
							val:        "\"",
							ignoreCase: false,
						},
					},
					&anyMatcher{
						line: 183, col: 26, offset: 4745,
					},
				},
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 185, col: 1, offset: 4748},
			expr: &oneOrMoreExpr{
				pos: position{line: 185, col: 19, offset: 4766},
				expr: &charClassMatcher{
					pos:        position{line: 185, col: 19, offset: 4766},
					val:        "[ \\t\\r\\n]",
					chars:      []rune{' ', '\t', '\r', '\n'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 187, col: 1, offset: 4778},
			expr: &notExpr{
				pos: position{line: 187, col: 8, offset: 4785},
				expr: &anyMatcher{
					line: 187, col: 9, offset: 4786,
				},
			},
		},
	},
}

func (c *current) onInput1(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonInput1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInput1(stack["expr"])
}

func (c *current) onOrExpression2(left, right interface{}) (interface{}, error) {
	return &BinaryExpr{
		Operator: BinaryOpOr,
		Left:     left.(Expr),
		Right:    right.(Expr),
	}, nil
}

func (p *parser) callonOrExpression2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrExpression2(stack["left"], stack["right"])
}

func (c *current) onOrExpression11(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonOrExpression11() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrExpression11(stack["expr"])
}

func (c *current) onAndExpression2(left, right interface{}) (interface{}, error) {
	return &BinaryExpr{
		Operator: BinaryOpAnd,
		Left:     left.(Expr),
		Right:    right.(Expr),
	}, nil
}

func (p *parser) callonAndExpression2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAndExpression2(stack["left"], stack["right"])
}

func (c *current) onAndExpression11(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonAndExpression11() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAndExpression11(stack["expr"])
}

func (c *current) onNotExpression2(expr interface{}) (interface{}, error) {
	if unary, ok := expr.(*UnaryExpr); ok && unary.Operator == UnaryOpNot {
		// small optimization to get rid unnecessary levels of AST nodes
		// for things like:  not not foo == 3  which is equivalent to foo == 3
		return unary.Operand, nil
	}

	return &UnaryExpr{
		Operator: UnaryOpNot,
		Operand:  expr.(Expr),
	}, nil
}

func (p *parser) callonNotExpression2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNotExpression2(stack["expr"])
}

func (c *current) onNotExpression8(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonNotExpression8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNotExpression8(stack["expr"])
}

func (c *current) onParenthesizedExpression2(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonParenthesizedExpression2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParenthesizedExpression2(stack["expr"])
}

func (c *current) onParenthesizedExpression12(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonParenthesizedExpression12() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParenthesizedExpression12(stack["expr"])
}

func (c *current) onParenthesizedExpression24() (bool, error) {
	return false, errors.New("Unmatched parentheses")
}

func (p *parser) callonParenthesizedExpression24() (bool, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParenthesizedExpression24()
}

func (c *current) onMatchSelectorOpValue1(selector, operator, value interface{}) (interface{}, error) {
	return &MatchExpr{Selector: selector.(Selector), Operator: operator.(MatchOperator), Value: value.(*Value)}, nil
}

func (p *parser) callonMatchSelectorOpValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchSelectorOpValue1(stack["selector"], stack["operator"], stack["value"])
}

func (c *current) onMatchSelectorOp1(selector, operator interface{}) (interface{}, error) {
	return &MatchExpr{Selector: selector.(Selector), Operator: operator.(MatchOperator), Value: nil}, nil
}

func (p *parser) callonMatchSelectorOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchSelectorOp1(stack["selector"], stack["operator"])
}

func (c *current) onMatchValueOpSelector2(value, operator, selector interface{}) (interface{}, error) {
	return &MatchExpr{Selector: selector.(Selector), Operator: operator.(MatchOperator), Value: value.(*Value)}, nil
}

func (p *parser) callonMatchValueOpSelector2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchValueOpSelector2(stack["value"], stack["operator"], stack["selector"])
}

func (c *current) onMatchValueOpSelector20(operator interface{}) (bool, error) {
	return false, errors.New("Invalid selector")
}

func (p *parser) callonMatchValueOpSelector20() (bool, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchValueOpSelector20(stack["operator"])
}

func (c *current) onMatchEqual1() (interface{}, error) {
	return MatchEqual, nil
}

func (p *parser) callonMatchEqual1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchEqual1()
}

func (c *current) onMatchNotEqual1() (interface{}, error) {
	return MatchNotEqual, nil
}

func (p *parser) callonMatchNotEqual1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchNotEqual1()
}

func (c *current) onMatchIsEmpty1() (interface{}, error) {
	return MatchIsEmpty, nil
}

func (p *parser) callonMatchIsEmpty1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchIsEmpty1()
}

func (c *current) onMatchIsNotEmpty1() (interface{}, error) {
	return MatchIsNotEmpty, nil
}

func (p *parser) callonMatchIsNotEmpty1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchIsNotEmpty1()
}

func (c *current) onMatchIn1() (interface{}, error) {
	return MatchIn, nil
}

func (p *parser) callonMatchIn1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchIn1()
}

func (c *current) onMatchNotIn1() (interface{}, error) {
	return MatchNotIn, nil
}

func (p *parser) callonMatchNotIn1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchNotIn1()
}

func (c *current) onMatchContains1() (interface{}, error) {
	return MatchIn, nil
}

func (p *parser) callonMatchContains1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchContains1()
}

func (c *current) onMatchNotContains1() (interface{}, error) {
	return MatchNotIn, nil
}

func (p *parser) callonMatchNotContains1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchNotContains1()
}

func (c *current) onSelector1(first, rest interface{}) (interface{}, error) {
	sel := Selector{
		first.(string),
	}

	if rest != nil {
		for _, v := range rest.([]interface{}) {
			sel = append(sel, v.(string))
		}
	}
	return sel, nil
}

func (p *parser) callonSelector1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSelector1(stack["first"], stack["rest"])
}

func (c *current) onIdentifier1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonIdentifier1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifier1()
}

func (c *current) onSelectorOrIndex2(ident interface{}) (interface{}, error) {
	return ident, nil
}

func (p *parser) callonSelectorOrIndex2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSelectorOrIndex2(stack["ident"])
}

func (c *current) onSelectorOrIndex7(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonSelectorOrIndex7() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSelectorOrIndex7(stack["expr"])
}

func (c *current) onIndexExpression2(lit interface{}) (interface{}, error) {
	return lit, nil
}

func (p *parser) callonIndexExpression2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIndexExpression2(stack["lit"])
}

func (c *current) onIndexExpression18() (bool, error) {
	return false, errors.New("Invalid index")
}

func (p *parser) callonIndexExpression18() (bool, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIndexExpression18()
}

func (c *current) onIndexExpression28() (bool, error) {
	return false, errors.New("Unclosed index expression")
}

func (p *parser) callonIndexExpression28() (bool, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIndexExpression28()
}

func (c *current) onValue2(selector interface{}) (interface{}, error) {
	return &Value{Raw: strings.Join(selector.(Selector), ".")}, nil
}

func (p *parser) callonValue2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValue2(stack["selector"])
}

func (c *current) onValue5(n interface{}) (interface{}, error) {
	return &Value{Raw: n.(string)}, nil
}

func (p *parser) callonValue5() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValue5(stack["n"])
}

func (c *current) onValue8(s interface{}) (interface{}, error) {
	return &Value{Raw: s.(string)}, nil
}

func (p *parser) callonValue8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValue8(stack["s"])
}

func (c *current) onNumberLiteral2() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonNumberLiteral2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumberLiteral2()
}

func (c *current) onNumberLiteral19() (bool, error) {
	return false, errors.New("Invalid number literal")
}

func (p *parser) callonNumberLiteral19() (bool, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumberLiteral19()
}

func (c *current) onStringLiteral2() (interface{}, error) {
	return strconv.Unquote(string(c.text))
}

func (p *parser) callonStringLiteral2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringLiteral2()
}

func (c *current) onStringLiteral25() (bool, error) {
	return false, errors.New("Unterminated string literal")
}

func (p *parser) callonStringLiteral25() (bool, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringLiteral25()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return fmt.Sprintf("%d:%d [%d]", p.line, p.col, p.offset)
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return fmt.Sprintf("%s %s %s", strings.Join(list[:len(list)-1], sep), lastSep, list[len(list)-1])
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}

		val = actVal
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	pt := p.pt
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			return val, ok
		}
	}
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	ignoreCase := ""
	if lit.ignoreCase {
		ignoreCase = "i"
	}
	val := fmt.Sprintf("%q%s", lit.val, ignoreCase)
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, val)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, val)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	pt := p.pt
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
